name = "Craftoria"
author = "TeamAOE"
version = "1.26.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4ed3eaeec3f9c99a164bec4cab0538fd7359dd30caa2537548cfbd9b6d56e71"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
