name = "Craftoria"
author = "TeamAOE"
version = "1.25.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "022b88e8a4c635c4b5ed15e826bd4c6a4d20137a698f063410323db50966efd3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
