name = "Craftoria"
author = "TeamAOE"
version = "1.27.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee1163eb4eec60b824572f0ce0d0fe985bd0d0f8770ce1551bf3f880d1f53692"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
