name = "Craftoria"
author = "TeamAOE"
version = "1.25.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a393e4750879dfc346f3b3d794dfe98f2de7f63262d4978a5f27aed163be181c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
