name = "Craftoria"
author = "TeamAOE"
version = "1.25.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9a9895bc9c6d764c0b7d6e9514d7d28d56723602f1cef9383e500f1283ef771"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
