name = "Craftoria"
author = "TeamAOE"
version = "1.25.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "966d209ab0eb4c85041ab2695adb6f200f5535f399300e3d02665d8cc462f584"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
