# Don't change this! Version used to track needed updates.
version = 0
chickenFeathers = true
parrotFeathers = true
snowGolemSnowflakes = true
allayMagicDensity = 0.2
vexMagicDensity = 0.2
sheepShearFluff = true
improvedDragonFireballTrail = true
dragonsBreathClouds = true
commandBlockMinecartParticles = "ON"
endCrystalParticles = true
minecartSparksDisplayType = "DEFAULT"
minecartSparksDensity = 0.5
slimeTrails = true
magmaCubeTrails = true
replaceSlimeSquishParticles = true
replaceOozingEffectParticles = true
replaceSpellCasterParticles = true
ironGolemCrackParticles = true
spectralArrowParticles = true
wardenDeathSoulParticles = true
freezingSnowFlakes = true
featherTicklingPandas = true
improvedPandaSneezes = true
villagerWorkAtWorkstationParticles = true
improvedBrownMooshroomFeedingEffects = true
improvedMooshroomShearingEffects = true
replaceBlazeSmoke = true
animalFeedingParticles = true
animalFeedingSoundVolume = 1.0
underwaterEntityPoofBubbles = true
improvedWetWolfShakeEffects = true
improvedVillagerSweatingEffects = true

[sleeping]
playerSnoreChance = 1.0
playerSnoreSoundVolume = 1.0
playersHaveSleepingZs = true
villagerSnoreChance = 1.0
villagerSnoreSoundVolume = 1.0
villagersHaveSleepingZs = true
foxesHaveSleepingZs = true
batsHaveSleepingZs = true
catsHaveSleepingZs = true
otherMobsHaveSleepingZs = true
displaySleepingZsOnlyWhenSnoring = false
adjustNameTagWhenSleeping = true

[humanoids]
drowningBubblesDisplayType = "THIRD_PERSON_ONLY"
drowningBubblesDensity = 3
drowningBubbleAlpha = 1.0
forceDrowningBubblesToColumn = false
potionRingsDisplayType = "DEFAULT"
potionRingsParticleType = "BOTH"
potionRingsScale = 1.0
potionRingsAlpha = 1.0
NPCsHavePotionRings = true

[humanoids.frostyBreath]
displayType = "THIRD_PERSON_ONLY"
alpha = 0.5
waitTime = 60
seasons = "DEFAULT"
additionalBiomes = [  ]

[humanoids.player]
enableBreathingEffectsInCreative = true
stomachGrowlingThreshold = 6
stomachGrowlingVolume = 1.0
stomachGrowlingWaitTime = 15
heartBeatingThreshold = 6
heartbeatVolume = 1.0
heartBeatingWaitTime = 3

[dustClouds]
scale = 2.0
alpha = 1.0
preventWhenRaining = false
flyIntoWall = true
lessViewBlocking = false
playerFell = true
mobFell = true
landMaceAttack = true
playerRunning = false
mobRunning = false
playerRunningRequiresSpeed = false

[burning]
smoke = "DEFAULT"
flames = true
sparks = true
sounds = true
extinguishSteam = true

[explosives]
tntUpdateSmoke = true
tntFlamesDensity = 1
tntSparks = true
creeperSmoke = "UPDATED"
creeperSparks = true

[splashes]
splashEffects = true
splashRipples = true
splashDroplets = true
splashBubbles = true
explosionsCauseSplashes = true
splashOverlayTint = 0.2
splashOverlayAlpha = 0.8
splashVelocityThreshold = 0.35
entityBlocklist = [  ]
secondarySplash = true
secondarySplashRipples = false
secondarySplashVelocityThreshold = 0.3
lavaSplashes = true
lavaSplashRipples = true