#Tier Config. This config is synced from server to client.
[tier]

	#Items
	[tier.Items]

		#QIO Drivers
		[tier.Items.qio_drivers]
			#The number of items that the Absolute QIO Drive can store.
			# Default: 128000000000
			# Range: 1 ~ 9223372036854775807
			absoluteCount = 128000000000
			#The number of types that the Absolute QIO Drive can store.
			# Default: 16384
			# Range: > 1
			absoluteTypes = 16384
			#The number of items that the Supreme QIO Drive can store.
			# Default: 1048000000000
			# Range: 1 ~ 9223372036854775807
			supremeCount = 1048000000000
			#The number of types that the Supreme QIO Drive can store.
			# Default: 65536
			# Range: > 1
			supremeTypes = 65536
			#The number of items that the Cosmic QIO Drive can store.
			# Default: 8000000000000
			# Range: 1 ~ 9223372036854775807
			cosmicCount = 8000000000000
			#The number of types that the Cosmic QIO Drive can store.
			# Default: 262144
			# Range: > 1
			cosmicTypes = 262144
			#The number of items that the Infinite QIO Drive can store.
			# Default: 16000000000000
			# Range: 1 ~ 9223372036854775807
			infiniteCount = 16000000000000
			#The number of types that the Infinite QIO Drive can store.
			# Default: 1048576
			# Range: > 1
			infiniteTypes = 1048576

	#Storages
	[tier.Storages]

		#Bins
		[tier.Storages.bins]
			#The number of items Absolute bins can store.
			# Default: 2097152
			# Range: > 1
			absoluteStorage = 2097152
			#The number of items Supreme bins can store.
			# Default: 16777216
			# Range: > 1
			supremeStorage = 16777216
			#The number of items Cosmic bins can store.
			# Default: 134217728
			# Range: > 1
			cosmicStorage = 134217728
			#The number of items Infinite bins can store.
			# Default: 1073741824
			# Range: > 1
			infiniteStorage = 1073741824

		#Induction
		[tier.Storages.induction]
			#Maximum number of Joules Absolute induction cells can store.
			# Default: 32768000000000
			# Range: 1 ~ 9223372036854775807
			absoluteStorage = 32768000000000
			#Maximum number of Joules Supreme induction cells can store.
			# Default: 262144000000000
			# Range: 1 ~ 9223372036854775807
			supremeStorage = 262144000000000
			#Maximum number of Joules Cosmic induction cells can store.
			# Default: 2097152000000000
			# Range: 1 ~ 9223372036854775807
			cosmicStorage = 2097152000000000
			#Maximum number of Joules Infinite induction cells can store.
			# Default: 9223372036854775807
			# Range: 1 ~ 9223372036854775807
			infiniteStorage = 9223372036854775807
			#Maximum number of Joules Absolute induction providers can output or accept.
			# Default: 1048576000
			# Range: 1 ~ 9223372036854775807
			absoluteOutput = 1048576000
			#Maximum number of Joules Supreme induction providers can output or accept.
			# Default: 8388608000
			# Range: 1 ~ 9223372036854775807
			supremeOutput = 8388608000
			#Maximum number of Joules Cosmic induction providers can output or accept.
			# Default: 67108864000
			# Range: 1 ~ 9223372036854775807
			cosmicOutput = 67108864000
			#Maximum number of Joules Infinite induction providers can output or accept.
			# Default: 536870912000
			# Range: 1 ~ 9223372036854775807
			infiniteOutput = 536870912000

		#Energy Cubes
		[tier.Storages.energy_cubes]
			#Maximum number of Joules Absolute energy cubes can store.
			# Default: 1024000000
			# Range: 1 ~ 9223372036854775807
			absoluteStorage = 1024000000
			#Output rate in Joules of Absolute energy cubes.
			# Default: 1024000
			# Range: 1 ~ 9223372036854775807
			absoluteOutput = 1024000
			#Maximum number of Joules Supreme energy cubes can store.
			# Default: 4096000000
			# Range: 1 ~ 9223372036854775807
			supremeStorage = 4096000000
			#Output rate in Joules of Supreme energy cubes.
			# Default: 4096000
			# Range: 1 ~ 9223372036854775807
			supremeOutput = 4096000
			#Maximum number of Joules Cosmic energy cubes can store.
			# Default: 16384000000
			# Range: 1 ~ 9223372036854775807
			cosmicStorage = 16384000000
			#Output rate in Joules of Cosmic energy cubes.
			# Default: 16384000
			# Range: 1 ~ 9223372036854775807
			cosmicOutput = 16384000
			#Maximum number of Joules Infinite energy cubes can store.
			# Default: 65536000000
			# Range: 1 ~ 9223372036854775807
			infiniteStorage = 65536000000
			#Output rate in Joules of Infinite energy cubes.
			# Default: 65536000
			# Range: 1 ~ 9223372036854775807
			infiniteOutput = 65536000

		#Fluid Tanks
		[tier.Storages.fluid_tanks]
			#Storage size of Absolute fluid tanks in mB.
			# Default: 4096000
			# Range: > 1
			absoluteStorage = 4096000
			#Output rate of Absolute fluid tanks in mB.
			# Default: 2048000
			# Range: > 1
			absoluteOutput = 2048000
			#Storage size of Supreme fluid tanks in mB.
			# Default: 32768000
			# Range: > 1
			supremeStorage = 32768000
			#Output rate of Supreme fluid tanks in mB.
			# Default: 16384000
			# Range: > 1
			supremeOutput = 16384000
			#Storage size of Cosmic fluid tanks in mB.
			# Default: 262144000
			# Range: > 1
			cosmicStorage = 262144000
			#Output rate of Cosmic fluid tanks in mB.
			# Default: 131072000
			# Range: > 1
			cosmicOutput = 131072000
			#Storage size of Infinite fluid tanks in mB.
			# Default: 2097152000
			# Range: > 1
			infiniteStorage = 2097152000
			#Output rate of Infinite fluid tanks in mB.
			# Default: 1048576000
			# Range: > 1
			infiniteOutput = 1048576000

		#Chemical Tanks
		[tier.Storages.chemical_tanks]
			#Storage size of Absolute chemical tanks in mB.
			# Default: 32768000
			# Range: 1 ~ 9223372036854775807
			absoluteStorage = 32768000
			#Output rate of Absolute chemical tanks in mB.
			# Default: 2048000
			# Range: 1 ~ 9223372036854775807
			absoluteOutput = 2048000
			#Storage size of Supreme chemical tanks in mB.
			# Default: 131072000
			# Range: 1 ~ 9223372036854775807
			supremeStorage = 131072000
			#Output rate of Supreme chemical tanks in mB.
			# Default: 8192000
			# Range: 1 ~ 9223372036854775807
			supremeOutput = 8192000
			#Storage size of Cosmic chemical tanks in mB.
			# Default: 524288000
			# Range: 1 ~ 9223372036854775807
			cosmicStorage = 524288000
			#Output rate of Cosmic chemical tanks in mB.
			# Default: 32768000
			# Range: 1 ~ 9223372036854775807
			cosmicOutput = 32768000
			#Storage size of Infinite chemical tanks in mB.
			# Default: 4194304000
			# Range: 1 ~ 9223372036854775807
			infiniteStorage = 4194304000
			#Output rate of Infinite chemical tanks in mB.
			# Default: 131072000
			# Range: 1 ~ 9223372036854775807
			infiniteOutput = 131072000

		#Radioactive Barrel
		[tier.Storages.radioactive_waste_barrel]
			#Amount of gas (mB) that can be stored in Absolute Radioactive Waste Barrel.
			# Default: 2048000
			# Range: 1 ~ 9223372036854775807
			absoluteStorage = 2048000
			#Number of ticks required for radioactive gas stored in Absolute Radioactive Waste Barrel to decay radioactiveWasteBarrelDecayAmount mB.
			# Default: 20
			# Range: > 1
			absoluteProcessTicks = 20
			#Number of mB of gas that decay every radioactiveWasteBarrelProcessTicks ticks when stored in Absolute Radioactive Waste Barrel. Set to zero to disable decay all together. (Gases in the mekanism:waste_barrel_decay_blacklist tag will not decay).
			# Default: 4
			# Range: 0 ~ 9223372036854775807
			absoluteDecayAmount = 4
			#Amount of gas (mB) that can be stored in Supreme Radioactive Waste Barrel.
			# Default: 8192000
			# Range: 1 ~ 9223372036854775807
			supremeStorage = 8192000
			#Number of ticks required for radioactive gas stored in Supreme Radioactive Waste Barrel to decay radioactiveWasteBarrelDecayAmount mB.
			# Default: 10
			# Range: > 1
			supremeProcessTicks = 10
			#Number of mB of gas that decay every radioactiveWasteBarrelProcessTicks ticks when stored in Supreme Radioactive Waste Barrel. Set to zero to disable decay all together. (Gases in the mekanism:waste_barrel_decay_blacklist tag will not decay).
			# Default: 16
			# Range: 0 ~ 9223372036854775807
			supremeDecayAmount = 16
			#Amount of gas (mB) that can be stored in Cosmic Radioactive Waste Barrel.
			# Default: 32768000
			# Range: 1 ~ 9223372036854775807
			cosmicStorage = 32768000
			#Number of ticks required for radioactive gas stored in Cosmic Radioactive Waste Barrel to decay radioactiveWasteBarrelDecayAmount mB.
			# Default: 5
			# Range: > 1
			cosmicProcessTicks = 5
			#Number of mB of gas that decay every radioactiveWasteBarrelProcessTicks ticks when stored in Cosmic Radioactive Waste Barrel. Set to zero to disable decay all together. (Gases in the mekanism:waste_barrel_decay_blacklist tag will not decay).
			# Default: 64
			# Range: 0 ~ 9223372036854775807
			cosmicDecayAmount = 64
			#Amount of gas (mB) that can be stored in Infinite Radioactive Waste Barrel.
			# Default: 131072000
			# Range: 1 ~ 9223372036854775807
			infiniteStorage = 131072000
			#Number of ticks required for radioactive gas stored in Infinite Radioactive Waste Barrel to decay radioactiveWasteBarrelDecayAmount mB.
			# Default: 5
			# Range: > 1
			infiniteProcessTicks = 5
			#Number of mB of gas that decay every radioactiveWasteBarrelProcessTicks ticks when stored in Infinite Radioactive Waste Barrel. Set to zero to disable decay all together. (Gases in the mekanism:waste_barrel_decay_blacklist tag will not decay).
			# Default: 256
			# Range: 0 ~ 9223372036854775807
			infiniteDecayAmount = 256

	#Transmitters
	[tier.transmitters]

		#Universal Cables
		[tier.transmitters.energy]
			#Internal buffer in Joules of Absolute Universal Cable.
			# Default: 65536000
			# Range: 1 ~ 9223372036854775807
			absoluteUniversalCable = 65536000
			#Internal buffer in Joules of Supreme Universal Cable.
			# Default: 524288000
			# Range: 1 ~ 9223372036854775807
			supremeUniversalCable = 524288000
			#Internal buffer in Joules of Cosmic Universal Cable.
			# Default: 4194304000
			# Range: 1 ~ 9223372036854775807
			cosmicUniversalCable = 4194304000
			#Internal buffer in Joules of Infinite Universal Cable.
			# Default: 33554432000
			# Range: 1 ~ 9223372036854775807
			infiniteUniversalCable = 33554432000

		#Mechanical Pipes
		[tier.transmitters.fluid]
			#Capacity of Absolute Mechanical Pipe in mb.
			# Default: 512000
			# Range: 1 ~ 9223372036854775807
			absoluteMechanicalPipesCapacity = 512000
			#Pump rate of Absolute Mechanical Pipe in mb.
			# Default: 128000
			# Range: 1 ~ 2147483647
			absoluteMechanicalPipesPullAmount = 128000
			#Capacity of Supreme Mechanical Pipe in mb.
			# Default: 2048000
			# Range: 1 ~ 9223372036854775807
			supremeMechanicalPipesCapacity = 2048000
			#Pump rate of Supreme Mechanical Pipe in mb.
			# Default: 512000
			# Range: 1 ~ 2147483647
			supremeMechanicalPipesPullAmount = 512000
			#Capacity of Cosmic Mechanical Pipe in mb.
			# Default: 8192000
			# Range: 1 ~ 9223372036854775807
			cosmicMechanicalPipesCapacity = 8192000
			#Pump rate of Cosmic Mechanical Pipe in mb.
			# Default: 2048000
			# Range: 1 ~ 2147483647
			cosmicMechanicalPipesPullAmount = 2048000
			#Capacity of Infinite Mechanical Pipe in mb.
			# Default: 32768000
			# Range: 1 ~ 9223372036854775807
			infiniteMechanicalPipesCapacity = 32768000
			#Pump rate of Infinite Mechanical Pipe in mb.
			# Default: 8192000
			# Range: 1 ~ 2147483647
			infiniteMechanicalPipesPullAmount = 8192000

		#Pressurized Tubes
		[tier.transmitters.chemical]
			#Capacity of Absolute Pressurized Tube in mb.
			# Default: 4096000
			# Range: 1 ~ 9223372036854775807
			absolutePressurizedTubesCapacity = 4096000
			#Pump rate of Absolute Pressurized Tube in mb.
			# Default: 1024000
			# Range: 1 ~ 9223372036854775807
			absolutePressurizedTubesPullAmount = 1024000
			#Capacity of Supreme Pressurized Tube in mb.
			# Default: 16384000
			# Range: 1 ~ 9223372036854775807
			supremePressurizedTubesCapacity = 16384000
			#Pump rate of Supreme Pressurized Tube in mb.
			# Default: 4096000
			# Range: 1 ~ 9223372036854775807
			supremePressurizedTubesPullAmount = 4096000
			#Capacity of Cosmic Pressurized Tube in mb.
			# Default: 65536000
			# Range: 1 ~ 9223372036854775807
			cosmicPressurizedTubesCapacity = 65536000
			#Pump rate of Cosmic Pressurized Tube in mb.
			# Default: 16384000
			# Range: 1 ~ 9223372036854775807
			cosmicPressurizedTubesPullAmount = 16384000
			#Capacity of Infinite Pressurized Tube in mb.
			# Default: 262144000
			# Range: 1 ~ 9223372036854775807
			infinitePressurizedTubesCapacity = 262144000
			#Pump rate of Infinite Pressurized Tube in mb.
			# Default: 65536000
			# Range: 1 ~ 9223372036854775807
			infinitePressurizedTubesPullAmount = 65536000

		#Logistical Transporters
		[tier.transmitters.item]
			#Five times the travel speed in m/s of Absolute Logistical Transporter.
			# Default: 55
			# Range: 1 ~ 2147483647
			absoluteLogisticalTransporterSpeed = 55
			#Item throughput rate of Absolute Logistical Transporter in items/half second.
			# Default: 128
			# Range: 1 ~ 2147483647
			absoluteLogisticalTransporterPullAmount = 128
			#Five times the travel speed in m/s of Absolute Logistical Transporter.
			# Default: 60
			# Range: 1 ~ 2147483647
			supremeLogisticalTransporterSpeed = 60
			#Item throughput rate of Supreme Logistical Transporter in items/half second.
			# Default: 256
			# Range: 1 ~ 2147483647
			supremeLogisticalTransporterPullAmount = 256
			#Five times the travel speed in m/s of Cosmic Logistical Transporter.
			# Default: 70
			# Range: 1 ~ 2147483647
			cosmicLogisticalTransporterSpeed = 70
			#Item throughput rate of Cosmic Logistical Transporter in items/half second.
			# Default: 512
			# Range: 1 ~ 2147483647
			cosmicLogisticalTransporterPullAmount = 512
			#Five times the travel speed in m/s of Cosmic Logistical Transporter.
			# Default: 100
			# Range: 1 ~ 2147483647
			infiniteLogisticalTransporterSpeed = 100
			#Item throughput rate of Infinite Logistical Transporter in items/half second.
			# Default: 1024
			# Range: 1 ~ 2147483647
			infiniteLogisticalTransporterPullAmount = 1024

		#Thermodynamic Conductors
		[tier.transmitters.heat]
			#Conduction value of Absolute Thermodynamic Conductor.
			# Default: 10
			# Range: 1 ~ 9223372036854775807
			absoluteThermodynamicConductorConduction = 10
			#Heat capacity of Absolute Thermodynamic Conductor.
			# Default: 1
			# Range: 1 ~ 9223372036854775807
			absoluteThermodynamicConductornCapacity = 1
			#Insulation value of Absolute Thermodynamic Conductor.
			# Default: 400000
			# Range: 1 ~ 9223372036854775807
			absoluteThermodynamicConductornInsulation = 400000
			#Conduction value of Supreme Thermodynamic Conductor.
			# Default: 15
			# Range: 1 ~ 9223372036854775807
			supremeThermodynamicConductorConduction = 15
			#Heat capacity of Supreme Thermodynamic Conductor.
			# Default: 1
			# Range: 1 ~ 9223372036854775807
			supremeThermodynamicConductornCapacity = 1
			#Insulation value of Supreme Thermodynamic Conductor.
			# Default: 800000
			# Range: 1 ~ 9223372036854775807
			supremeThermodynamicConductornInsulation = 800000
			#Conduction value of Cosmic Thermodynamic Conductor.
			# Default: 20
			# Range: 1 ~ 9223372036854775807
			cosmicThermodynamicConductorConduction = 20
			#Heat capacity of Cosmic Thermodynamic Conductor.
			# Default: 1
			# Range: 1 ~ 9223372036854775807
			cosmicThermodynamicConductornCapacity = 1
			#Insulation value of Cosmic Thermodynamic Conductor.
			# Default: 1000000
			# Range: 1 ~ 9223372036854775807
			cosmicThermodynamicConductornInsulation = 1000000
			#Conduction value of Infinite Thermodynamic Conductor.
			# Default: 25
			# Range: 1 ~ 9223372036854775807
			infiniteThermodynamicConductorConduction = 25
			#Heat capacity of Infinite Thermodynamic Conductor.
			# Default: 1
			# Range: 1 ~ 9223372036854775807
			infiniteThermodynamicConductornCapacity = 1
			#Insulation value of Infinite Thermodynamic Conductor.
			# Default: 4000000
			# Range: 1 ~ 9223372036854775807
			infiniteThermodynamicConductornInsulation = 4000000
