#Generator Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	#Range: 1 ~ 9223372036854775807
	heatGenerator = 160000
	#Base energy storage (Joules).
	#Range: 1 ~ 9223372036854775807
	bioGenerator = 160000
	#Base energy storage (Joules).
	#Range: 1 ~ 9223372036854775807
	solarGenerator = 96000
	#Base energy storage (Joules).
	#Range: 1 ~ 9223372036854775807
	advancedSolarGenerator = 200000
	#Base energy storage (Joules).
	#Range: 1 ~ 9223372036854775807
	windGenerator = 200000
