#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	enrichmentChamber = 50
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	osmiumCompressor = 100
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	combiner = 50
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	crusher = 50
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	metallurgicInfuser = 50
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	purificationChamber = 200
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	energizedSmelter = 50
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	digitalMiner = 1000
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	electricPump = 100
	#Energy that can be transferred at once per charge operation (Joules).
	#Range: 0 ~ 9223372036854775807
	chargePad = 1024000
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	rotaryCondensentrator = 50
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	chemicalOxidizer = 200
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	chemicalInfuser = 200
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	chemicalInjectionChamber = 400
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	precisionSawmill = 50
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	chemicalDissolutionChamber = 400
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	chemicalWasher = 200
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	chemicalCrystallizer = 400
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	seismicVibrator = 50
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	pressurizedReactionBase = 5
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	fluidicPlenisher = 100
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	laser = 10000
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	formulaicAssemblicator = 100
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	modificationStation = 400
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	isotopicCentrifuge = 200
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	nutritionalLiquifier = 200
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	antiprotonicNucleosynthesizer = 100000
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	pigmentExtractor = 200
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	pigmentMixer = 200
	#Energy per operation tick (Joules).
	#Range: 0 ~ 9223372036854775807
	paintingMachine = 100
	#Energy per chunk per tick (Joules).
	#Range: 0 ~ 9223372036854775807
	dimensionalStabilizer = 5000

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		#Range: 0 ~ 9223372036854775807
		teleporterBase = 1000
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		#Range: 0 ~ 9223372036854775807
		teleporterDistance = 10
		#Flat additional cost for interdimensional teleportation. Distance is still taken into account minimizing energy cost based on dimension scales.
		#Range: 0 ~ 9223372036854775807
		teleporterDimensionPenalty = 10000
