
#Mekanism Startup Config. This config is loaded on early, and requires a game restart to take effect, and is not synced automatically between client and server. It is highly recommended to ensure you are using the same values for this config on the server and client.
[startup]

	#Startup gear configs
	[startup.gear]

		#Free Runner Settings
		[startup.gear.free_runner]

			#Armored Free Runner Settings
			[startup.gear.free_runner.armored]
				#Armor value of the Armored Free Runners
				#Range: > 0
				armor = 3
				#Toughness value of the Armored Free Runners.
				#Range: 0.0 ~ 3.4028234663852886E38
				toughness = 2.0
				#Knockback resistance value of the Armored Free Runners.
				#Range: 0.0 ~ 3.4028234663852886E38
				knockbackResistance = 0.0

		#Jetpack Settings
		[startup.gear.jetpack]

			#Armored Jetpack Settings
			[startup.gear.jetpack.armored]
				#Armor value of the Armored Jetpack.
				#Range: > 0
				armor = 8
				#Toughness value of the Armored Jetpack.
				#Range: 0.0 ~ 3.4028234663852886E38
				toughness = 2.0
				#Knockback resistance value of the Armored Jetpack.
				#Range: 0.0 ~ 3.4028234663852886E38
				knockbackResistance = 0.0

		#MekaSuit Settings
		[startup.gear.mekasuit]
			#Armor value of MekaSuit Helmets.
			#Range: > 0
			helmetArmor = 3
			#Armor value of MekaSuit BodyArmor.
			#Range: > 0
			bodyArmorArmor = 8
			#Armor value of MekaSuit Pants.
			#Range: > 0
			pantsArmor = 6
			#Armor value of MekaSuit Boots.
			#Range: > 0
			bootsArmor = 3
			#Toughness value of the MekaSuit.
			#Range: 0.0 ~ 3.4028234663852886E38
			toughness = 3.0
			#Knockback resistance value of the MekaSuit.
			#Range: 0.0 ~ 3.4028234663852886E38
			knockbackResistance = 0.10000000149011612

