
#Mekanism Tools Config. This config is synced from server to client.
[tools]

	[tools.mobArmorSpawnRate]
		#The chance that Mekanism Armor can spawn on mobs. This is multiplied modified by the chunk's difficulty modifier. Vanilla uses 0.15 for its armor spawns, we use 0.1 as default to lower chances of mobs getting some vanilla and some mek armor.
		#Range: 0.0 ~ 1.0
		general = 0.1
		#The chance that Mekanism Weapons can spawn in a zombie's hand.
		#Range: 0.0 ~ 1.0
		weapon = 0.01
		#The chance that Mekanism Weapons can spawn in a zombie's hand when on hard difficulty.
		#Range: 0.0 ~ 1.0
		weaponHard = 0.05000000074505806

		#Spawn chances for pieces of Bronze gear. Note: These values are after the general mobArmorSpawnRate (or corresponding weapon rate) has been checked, and after an even split between material types has been done.
		[tools.mobArmorSpawnRate.bronze]
			#Whether mobs can spawn with Bronze Weapons.
			canSpawnWeapon = true
			#The chance that mobs will spawn with Bronze Swords rather than Bronze Shovels.
			#Range: 0.0 ~ 1.0
			swordWeight = 0.33
			#The chance that mobs can spawn with Bronze Helmets.
			#Range: 0.0 ~ 1.0
			helmetChance = 1.0
			#The chance that mobs can spawn with Bronze Chestplates.
			#Range: 0.0 ~ 1.0
			chestplateChance = 1.0
			#The chance that mobs can spawn with Bronze Leggings.
			#Range: 0.0 ~ 1.0
			leggingsChance = 1.0
			#The chance that mobs can spawn with Bronze Boots.
			#Range: 0.0 ~ 1.0
			bootsChance = 1.0
			#The chance that after each piece of Bronze Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChance = 0.25
			#The chance on hard mode that after each piece of Bronze Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChanceHard = 0.1
			#The chance that if a mob spawns with Bronze Weapons that it will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			weaponEnchantmentChance = 0.25
			#The chance that if a mob spawns with Bronze Armor that they will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			armorEnchantmentChance = 0.5

		#Spawn chances for pieces of Lapis Lazuli gear. Note: These values are after the general mobArmorSpawnRate (or corresponding weapon rate) has been checked, and after an even split between material types has been done.
		[tools.mobArmorSpawnRate.lapis_lazuli]
			#Whether mobs can spawn with Lapis Lazuli Weapons.
			canSpawnWeapon = true
			#The chance that mobs will spawn with Lapis Lazuli Swords rather than Lapis Lazuli Shovels.
			#Range: 0.0 ~ 1.0
			swordWeight = 0.33
			#The chance that mobs can spawn with Lapis Lazuli Helmets.
			#Range: 0.0 ~ 1.0
			helmetChance = 1.0
			#The chance that mobs can spawn with Lapis Lazuli Chestplates.
			#Range: 0.0 ~ 1.0
			chestplateChance = 1.0
			#The chance that mobs can spawn with Lapis Lazuli Leggings.
			#Range: 0.0 ~ 1.0
			leggingsChance = 1.0
			#The chance that mobs can spawn with Lapis Lazuli Boots.
			#Range: 0.0 ~ 1.0
			bootsChance = 1.0
			#The chance that after each piece of Lapis Lazuli Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChance = 0.25
			#The chance on hard mode that after each piece of Lapis Lazuli Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChanceHard = 0.1
			#The chance that if a mob spawns with Lapis Lazuli Weapons that it will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			weaponEnchantmentChance = 0.25
			#The chance that if a mob spawns with Lapis Lazuli Armor that they will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			armorEnchantmentChance = 0.5

		#Spawn chances for pieces of Osmium gear. Note: These values are after the general mobArmorSpawnRate (or corresponding weapon rate) has been checked, and after an even split between material types has been done.
		[tools.mobArmorSpawnRate.osmium]
			#Whether mobs can spawn with Osmium Weapons.
			canSpawnWeapon = true
			#The chance that mobs will spawn with Osmium Swords rather than Osmium Shovels.
			#Range: 0.0 ~ 1.0
			swordWeight = 0.33
			#The chance that mobs can spawn with Osmium Helmets.
			#Range: 0.0 ~ 1.0
			helmetChance = 1.0
			#The chance that mobs can spawn with Osmium Chestplates.
			#Range: 0.0 ~ 1.0
			chestplateChance = 1.0
			#The chance that mobs can spawn with Osmium Leggings.
			#Range: 0.0 ~ 1.0
			leggingsChance = 1.0
			#The chance that mobs can spawn with Osmium Boots.
			#Range: 0.0 ~ 1.0
			bootsChance = 1.0
			#The chance that after each piece of Osmium Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChance = 0.25
			#The chance on hard mode that after each piece of Osmium Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChanceHard = 0.1
			#The chance that if a mob spawns with Osmium Weapons that it will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			weaponEnchantmentChance = 0.25
			#The chance that if a mob spawns with Osmium Armor that they will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			armorEnchantmentChance = 0.5

		#Spawn chances for pieces of Refined Glowstone gear. Note: These values are after the general mobArmorSpawnRate (or corresponding weapon rate) has been checked, and after an even split between material types has been done.
		[tools.mobArmorSpawnRate.refined_glowstone]
			#Whether mobs can spawn with Refined Glowstone Weapons.
			canSpawnWeapon = true
			#The chance that mobs will spawn with Refined Glowstone Swords rather than Refined Glowstone Shovels.
			#Range: 0.0 ~ 1.0
			swordWeight = 0.33
			#The chance that mobs can spawn with Refined Glowstone Helmets.
			#Range: 0.0 ~ 1.0
			helmetChance = 1.0
			#The chance that mobs can spawn with Refined Glowstone Chestplates.
			#Range: 0.0 ~ 1.0
			chestplateChance = 1.0
			#The chance that mobs can spawn with Refined Glowstone Leggings.
			#Range: 0.0 ~ 1.0
			leggingsChance = 1.0
			#The chance that mobs can spawn with Refined Glowstone Boots.
			#Range: 0.0 ~ 1.0
			bootsChance = 1.0
			#The chance that after each piece of Refined Glowstone Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChance = 0.25
			#The chance on hard mode that after each piece of Refined Glowstone Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChanceHard = 0.1
			#The chance that if a mob spawns with Refined Glowstone Weapons that it will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			weaponEnchantmentChance = 0.25
			#The chance that if a mob spawns with Refined Glowstone Armor that they will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			armorEnchantmentChance = 0.5

		#Spawn chances for pieces of Refined Obsidian gear. Note: These values are after the general mobArmorSpawnRate (or corresponding weapon rate) has been checked, and after an even split between material types has been done.
		[tools.mobArmorSpawnRate.refined_obsidian]
			#Whether mobs can spawn with Refined Obsidian Weapons.
			canSpawnWeapon = true
			#The chance that mobs will spawn with Refined Obsidian Swords rather than Refined Obsidian Shovels.
			#Range: 0.0 ~ 1.0
			swordWeight = 0.33
			#The chance that mobs can spawn with Refined Obsidian Helmets.
			#Range: 0.0 ~ 1.0
			helmetChance = 1.0
			#The chance that mobs can spawn with Refined Obsidian Chestplates.
			#Range: 0.0 ~ 1.0
			chestplateChance = 1.0
			#The chance that mobs can spawn with Refined Obsidian Leggings.
			#Range: 0.0 ~ 1.0
			leggingsChance = 1.0
			#The chance that mobs can spawn with Refined Obsidian Boots.
			#Range: 0.0 ~ 1.0
			bootsChance = 1.0
			#The chance that after each piece of Refined Obsidian Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChance = 0.25
			#The chance on hard mode that after each piece of Refined Obsidian Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChanceHard = 0.1
			#The chance that if a mob spawns with Refined Obsidian Weapons that it will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			weaponEnchantmentChance = 0.25
			#The chance that if a mob spawns with Refined Obsidian Armor that they will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			armorEnchantmentChance = 0.5

		#Spawn chances for pieces of Steel gear. Note: These values are after the general mobArmorSpawnRate (or corresponding weapon rate) has been checked, and after an even split between material types has been done.
		[tools.mobArmorSpawnRate.steel]
			#Whether mobs can spawn with Steel Weapons.
			canSpawnWeapon = true
			#The chance that mobs will spawn with Steel Swords rather than Steel Shovels.
			#Range: 0.0 ~ 1.0
			swordWeight = 0.33
			#The chance that mobs can spawn with Steel Helmets.
			#Range: 0.0 ~ 1.0
			helmetChance = 1.0
			#The chance that mobs can spawn with Steel Chestplates.
			#Range: 0.0 ~ 1.0
			chestplateChance = 1.0
			#The chance that mobs can spawn with Steel Leggings.
			#Range: 0.0 ~ 1.0
			leggingsChance = 1.0
			#The chance that mobs can spawn with Steel Boots.
			#Range: 0.0 ~ 1.0
			bootsChance = 1.0
			#The chance that after each piece of Steel Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChance = 0.25
			#The chance on hard mode that after each piece of Steel Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChanceHard = 0.1
			#The chance that if a mob spawns with Steel Weapons that it will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			weaponEnchantmentChance = 0.25
			#The chance that if a mob spawns with Steel Armor that they will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			armorEnchantmentChance = 0.5

