#Whether to have selection render additive (default = false)
AdditiveShaderSelection = false
#Outline Red color value (default = 232)
# Default: 232
# Range: 1 ~ 255
MixedSelectionColorR = 232
#Outline Green color value (default = 232)
# Default: 232
# Range: 1 ~ 255
MixedSelectionColorG = 232
#Outline Blue color value (default = 232)
# Default: 232
# Range: 1 ~ 255
MixedSelectionColorB = 232
#Outline alpha value (default = 32)
# Default: 64
# Range: 1 ~ 255
MixedSelectionAlpha = 64
#Whether to blur the Face Texture of the Mixed Selection (default = false)
BlurFace = false
#Outline Red color value (default = 232)
# Default: 232
# Range: 1 ~ 255
DestroySelectionColorR = 232
#Outline Green color value (default = 232)
# Default: 128
# Range: 1 ~ 255
DestroySelectionColorG = 128
#Outline Blue color value (default = 232)
# Default: 128
# Range: 1 ~ 255
DestroySelectionColorB = 128
#Outline alpha value (default = 32)
# Default: 96
# Range: 1 ~ 255
DestroySelectionAlpha = 96
#Whether to blur the Face Texture of the Destroy Selection (default = true)
DestroyBlurFace = true
#Outline Red color value (default = 232)
# Default: 96
# Range: 1 ~ 255
InteractionSelectionColorR = 96
#Outline Green color value (default = 232)
# Default: 232
# Range: 1 ~ 255
InteractionSelectionColorG = 232
#Outline Blue color value (default = 232)
# Default: 128
# Range: 1 ~ 255
InteractionSelectionColorB = 128
#Outline alpha value (default = 32)
# Default: 96
# Range: 1 ~ 255
InteractionSelectionAlpha = 96
#Whether to blur the Face Texture of the Interaction Selection (default = true)
InteractionBlurFace = true
#Outline Red color value (default = 232)
# Default: 232
# Range: 1 ~ 255
WarnSelectionColorR = 232
#Outline Green color value (default = 232)
# Default: 96
# Range: 1 ~ 255
WarnSelectionColorG = 96
#Outline Blue color value (default = 232)
# Default: 96
# Range: 1 ~ 255
WarnSelectionColorB = 96
#Outline alpha value (default = 32)
# Default: 96
# Range: 1 ~ 255
WarnSelectionAlpha = 96
#Whether to blur the Face Texture of the Warn Selection (default = true)
WarnBlurFace = true
#Whether to have shadow behind of the Selection Text (default = false)
TextShadow = false
#Whether to have background behind of the Selection Text (default = false)
TextBackground = true
#Whether to have Selection Text on the left side of the screen (default = true)
TextLeftSide = true
#Whether to make the Activation Key Toggleable (default = false)
ToggleableKey = false
#Whether to disable selection scroll (default = false)
DisableScroll = false
#Outline thickness (default = 0.5)
# Default: 0.5
# Range: 0.1 ~ 16.0
OutlineThickness = 0.5
#Whether to render the Outline of the Selection (default = true)
RenderOutline = true
#Whether to render the Face Texture of the Selection (default = true)
RenderFace = true
#Ability to see your selection through Blocks whether the server allows it also (default = true)
XrayOutlineSelection = true
#Offset Y position of Selection Text (default = 0)
# Default: 0
# Range: > -2147483647
SelectionTextOffsetY = 34
#Offset Z position of Selection Text (default = 0)
# Default: 0
# Range: > -2147483647
SelectionTextOffsetX = 0
#Whether to display Current Mode Text above the hotbar or in chat (default = false)
DisplaySelectionInChat = false
#Maximum of Selection Blocks that can be viewed (default = 128)
# Default: 128
# Range: 0 ~ 2048
MaxBlockViewing = 128
#Whether to switch your Excavein Special Cosmetic Types if have one (default = 1) 
#0=DISABLE|1=ANNIVERSARY|2=CONTRIBUTOR|3=TEAM|4=･ω･
# Default: 1
# Range: 0 ~ 9999
CosmeticType = 1
#for Devs mainly (default = false)
Debug = false
