appearance = {display_description = true, tabs_alphabetic_order = true, criterias_alphabetic_order = true, background_style = "TRANSPARENT", criterias_translation_mode = "ONLY_COMPATIBLE", display_sideabar = true}
advanced_customization = {footer_height = 32, above_widget_limit = 14, below_widget_limit = 14, header_height = 48, criterias_width = 142}
