
["basic options"]
	"Enable weight for fish? Useful for fishing competitions" = false
	"Enable debug mode? (Enables additional logging)" = false
	"Show Fillet recipes in JEI?" = true
	#Range: -63 ~ 0
	"How many blocks below sea level Aquaculture fish can spawn" = 0

	["basic options"."Amount of Message In A Bottle messages"]
		#Range: 0 ~ 255
		" Used to add additional custom messages" = 29

["neptunium options"]
	"Enable recipes for Neptunium items?" = true
	"Enable recipes for Neptunium armor?" = true
	#Should Neptune's bounty be added as fishing loot? Very rare.
	"Add Neptune's Bounty as loot?" = true

