[basic_options]
	"Enable weight for fish? Useful for fishing competitions" = false
	# Default: 29
	# Range: 0 ~ 255
	"Amount of Message In A Bottle messages - Used to add additional custom messages" = 29
	"Enable debug mode? (Enables additional logging)" = false
	"Show Fillet recipes in JEI?" = true
	# Default: 13
	# Range: 0 ~ 63
	"How many blocks below sea level Aquaculture fish can spawn" = 13

[neptunium_options]
	"Enable recipes for Neptunium items?" = true
	"Enable recipes for Neptunium armor?" = true
	#Should Neptune's bounty be added as fishing loot? Very rare.
	"Add Neptune's Bounty as loot?" = true
	# Default: 1
	# Range: 1 ~ 100
	"Neptunium loot table weight - For reference; Fish loot table weight: 85, Junk loot table weight: 10" = 1
