# Default: 8.0
# Range: 2.0 ~ 100.0
maxShieldingAbsorption = 8.0
# Default: 0.2
# Range: 0.0 ~ 1.0
wildenSpellDamageBonus = 0.2
# Default: 0.2
# Range: 0.0 ~ 1.0
wildenMaxManaBonus = 0.2
# Default: 0.2
# Range: 0.0 ~ 1.0
wildenManaRegenBonus = 0.2
drygmyFarmingToolPlainCopy = false
# Default: 2
# Range: 0 ~ 10000
drygmyFarmingDamageTool = 2
