	#Setting these values to false will disable features using the vanilla isEnabled method
	#It is recommended to create a new world after changing the config!
	["Arts & Crafts Config".Features]
		#Allows flower pots to be dyed when true. Default value: true
		enableDyedFlowerPots = true
		#Should chalk sticks be enabled? Default value: true
		enableChalkSticks = true
		#Allows decorated pots to be dyed when true. Default value: true
		enableDyedDecoratedPots = true
