#General settings
[general]
	#The CurseForge project ID for the modpack
	# Default: 0
	# Range: > 0
	modpackProjectID = 1039252
	#The name of the modpack
	modpackName = "Craftoria"
	#The version of the modpack
	modpackVersion = "1.15.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false
