spawnPalms = true
spawnSeashells = true
spawnSandwaves = true

[messageInABottle]
	allowSpawning = true
	# Default: 2
	# Range: > 1
	maxCount = 2
	# Default: 6000
	# Range: > 20
	spawnInterval = 6000
