#Should the chat scramble when the player has the Tipsy effect?
#Default: true
scrambleChat = true
#Should other player's nametags scramble when the player has the Tipsy effect?
#Default: true
scrambleName = true
#Should signs scramble when the player has the Tipsy effect?
#Default: true
scrambleSign = true
#Should kegs render the fluid texture in the background of the fluid slot?
#Default: true
renderFluidInKeg = true
#Which unit the fluid display in the keg should use.
#Should be 'liters', 'millibuckets' or 'droplets'
#1 L = 1 mB = 81 d
#Default: millibuckets
fluidDisplayUnit = "millibuckets"
#When the opposite fluid display unit should be shown.
#Should be one of 'never', 'advanced_tooltips' or 'always'
#Default: never
oppositeFluidDisplay = "never"
#Should the numbed hearts obtained from being damaged when Tipsy flicker when you are about to take damage?
#Default: true
numbedHeartFlickering = true
#Should the food bar have a yellow overlay when the player has the Intoxication effect?
#Default: true
intoxicationFoodOverlay = true
