#List of blocks that are allowed to be covered. Supports '*' as a wildcard.
blocks = ["pipez:*_pipe", "mekanism:*_cable", "mekanism:*_conductor", "mekanism:*_pipe", "mekanism:*_tube", "mekanism:*_transporter", "mekanism_extras:*_cable", "mekanism_extras:*_conductor", "mekanism_extras:*_pipe", "mekanism_extras:*_tube", "mekanism_extras:*_transporter", "thermal:*_duct", "thermal:*_duct_windowed", "computercraft:cable", "powah:energy_cable_*", "pneumaticcraft:*_tube", "laserio:laser_*", "cyclic:*_pipe", "embers:*_pipe", "elementalcraft:elementpipe*", "gtceu:*wire", "gtceu:*pipe"]
#List of blocks that are explicitly not allowed to be used as a cover. Supports '*' as a wildcard.
not_allowed_blocks = []
#Whether the facade should be consumed when placed.
consumeFacade = true
#List of blocks that need z-fighting fixes. Supports '*' as a wildcard.
z_fighting = ["ae2:cable_bus"]
#List of blocks that should not render when covered by a facade. Supports '*' as a wildcard.
hidden_when_facaded = []
#Config version. Increment to apply changes.
# Default: 1
# Range: > 1
configVersion = 1
#Previous config version. Do not modify manually.
# Default: 0
# Range: > 0
lastConfigVersion = 0
#List of additional blocks added in this version.
added_blocks = ["modern_industrialization:pipe"]
#List of blocks from the previous version. Do not modify manually.
last_version_blocks = []
#Whether new blocks for the config should be fetched from the network.
auto_update_config = true
