#.
#Modify Create Encased blocks comportements
[kinetics]
	#.
	#.
	#Can swap casing between block (Mixer, Press, Depot, Gearbox, etc...)
	casingBlockSwappable = true
	#.
	#Can swap material between shafts,cogwheels and large cogwheels (includes brass,andesite and glass)
	shaftCogwheelsSwappable = true
	#.
	#Should Wooden Shaft break if the speed is too high
	shouldWoodenShaftBreak = true
	#.
	#Should Glass Shaft break if the system is overstressed
	shouldGlassShaftBreak = true
	#.
	#The max speed wooden shafts can endure
	# Default: 32
	# Range: 2 ~ 256
	maxSpeedWoodenShaft = 32
	#.
	#Defines if the configurable requires a shaft to add a shaft to a face
	configurableGearboxRequiresShaft = true
	#.
	#Defines if when the face is changed on the configurable gearbox, the opposite face should be also changed. It doesn't consume more shaft !
	configurableGearboxChangeTwoFaces = false

		#.
		#Fine tune the kinetic stats of individual components
		[kinetics.stressValues.v2]

			#.
			#.
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v2.impact]
				railway_encased_spruce_shaft = 0.0
				shadow_steel_encased_birch_large_cogwheel = 0.0
				refined_radiance_encased_mangrove_large_cogwheel = 0.0
				refined_radiance_encased_crimson_shaft = 0.0
				andesite_encased_oak_cogwheel = 0.0
				brass_encased_spruce_shaft = 0.0
				andesite_encased_bamboo_cogwheel = 0.0
				mldeg_shaft = 0.0
				creative_encased_mangrove_shaft = 0.0
				andesite_encased_jungle_shaft = 0.0
				shadow_steel_encased_dark_oak_cogwheel = 0.0
				creative_encased_birch_cogwheel = 0.0
				shadow_steel_encased_spruce_shaft = 0.0
				brass_encased_oak_shaft = 0.0
				industrial_iron_encased_bamboo_cogwheel = 0.0
				brass_encased_birch_large_cogwheel = 0.0
				railway_encased_warped_cogwheel = 0.0
				creative_encased_dark_oak_shaft = 0.0
				railway_mixer = 4.0
				copper_encased_mangrove_large_cogwheel = 0.0
				brass_encased_mangrove_large_cogwheel = 0.0
				refined_radiance_encased_acacia_shaft = 0.0
				shadow_steel_encased_bamboo_shaft = 0.0
				shadow_steel_encased_oak_shaft = 0.0
				creative_encased_jungle_large_cogwheel = 0.0
				refined_radiance_encased_glass_shaft = 0.0
				creative_encased_birch_shaft = 0.0
				acacia_large_cogwheel = 0.0
				brass_encased_jungle_large_cogwheel = 0.0
				shadow_steel_encased_warped_cogwheel = 0.0
				cherry_large_cogwheel = 0.0
				copper_encased_mangrove_cogwheel = 0.0
				industrial_iron_encased_birch_cogwheel = 0.0
				industrial_iron_encased_spruce_shaft = 0.0
				refined_radiance_encased_warped_cogwheel = 0.0
				creative_encased_crimson_shaft = 0.0
				refined_radiance_encased_cherry_shaft = 0.0
				copper_encased_warped_cogwheel = 0.0
				copper_encased_birch_shaft = 0.0
				glass_shaft = 0.0
				copper_encased_acacia_shaft = 0.0
				creative_encased_mangrove_cogwheel = 0.0
				copper_gearbox = 0.0
				industrial_iron_encased_dark_oak_shaft = 0.0
				creative_press = 8.0
				refined_radiance_encased_mldeg_shaft = 0.0
				copper_encased_cherry_shaft = 0.0
				cherry_shaft = 0.0
				creative_encased_jungle_cogwheel = 0.0
				refined_radiance_encased_oak_shaft = 0.0
				brass_encased_mangrove_cogwheel = 0.0
				andesite_encased_crimson_shaft = 0.0
				creative_encased_oak_shaft = 0.0
				railway_adjustable_chain_gearshift = 0.0
				shadow_steel_encased_crimson_cogwheel = 0.0
				mangrove_cogwheel = 0.0
				refined_radiance_encased_large_cogwheel = 0.0
				shadow_steel_encased_jungle_large_cogwheel = 0.0
				brass_encased_oak_large_cogwheel = 0.0
				brass_encased_bamboo_shaft = 0.0
				shadow_steel_encased_mldeg_shaft = 0.0
				industrial_iron_adjustable_chain_gearshift = 0.0
				creative_encased_bamboo_shaft = 0.0
				industrial_iron_encased_warped_large_cogwheel = 0.0
				railway_encased_dark_oak_cogwheel = 0.0
				railway_encased_chain_drive = 0.0
				railway_encased_bamboo_shaft = 0.0
				copper_encased_dark_oak_shaft = 0.0
				copper_encased_jungle_large_cogwheel = 0.0
				railway_encased_crimson_large_cogwheel = 0.0
				industrial_iron_encased_mangrove_shaft = 0.0
				copper_encased_warped_shaft = 0.0
				brass_encased_dark_oak_large_cogwheel = 0.0
				andesite_encased_mangrove_shaft = 0.0
				copper_press = 8.0
				andesite_encased_birch_shaft = 0.0
				acacia_shaft = 0.0
				andesite_encased_warped_large_cogwheel = 0.0
				railway_encased_cherry_large_cogwheel = 0.0
				industrial_iron_encased_birch_shaft = 0.0
				industrial_iron_encased_cherry_large_cogwheel = 0.0
				brass_press = 8.0
				shadow_steel_encased_crimson_shaft = 0.0
				brass_encased_mldeg_shaft = 0.0
				brass_encased_jungle_cogwheel = 0.0
				refined_radiance_encased_cherry_large_cogwheel = 0.0
				copper_encased_dark_oak_large_cogwheel = 0.0
				andesite_encased_bamboo_shaft = 0.0
				shadow_steel_encased_cogwheel = 0.0
				railway_encased_mangrove_large_cogwheel = 0.0
				industrial_iron_gearbox = 0.0
				andesite_encased_acacia_shaft = 0.0
				andesite_encased_cherry_large_cogwheel = 0.0
				industrial_iron_encased_birch_large_cogwheel = 0.0
				andesite_encased_dark_oak_cogwheel = 0.0
				crimson_cogwheel = 0.0
				refined_radiance_encased_jungle_cogwheel = 0.0
				refined_radiance_encased_jungle_large_cogwheel = 0.0
				railway_encased_birch_large_cogwheel = 0.0
				creative_encased_shaft = 0.0
				copper_encased_jungle_cogwheel = 0.0
				industrial_iron_encased_oak_large_cogwheel = 0.0
				oak_cogwheel = 0.0
				brass_encased_birch_shaft = 0.0
				andesite_encased_birch_cogwheel = 0.0
				dark_oak_shaft = 0.0
				copper_encased_crimson_cogwheel = 0.0
				acacia_cogwheel = 0.0
				copper_encased_shaft = 0.0
				industrial_iron_encased_warped_shaft = 0.0
				creative_encased_cherry_cogwheel = 0.0
				copper_encased_bamboo_cogwheel = 0.0
				industrial_iron_press = 8.0
				andesite_encased_spruce_shaft = 0.0
				jungle_shaft = 0.0
				copper_encased_acacia_cogwheel = 0.0
				jungle_cogwheel = 0.0
				railway_encased_glass_shaft = 0.0
				andesite_encased_acacia_large_cogwheel = 0.0
				refined_radiance_encased_acacia_cogwheel = 0.0
				creative_encased_cogwheel = 0.0
				copper_encased_mangrove_shaft = 0.0
				brass_encased_bamboo_large_cogwheel = 0.0
				creative_gearbox = 0.0
				andesite_encased_jungle_large_cogwheel = 0.0
				industrial_iron_encased_glass_shaft = 0.0
				brass_encased_cherry_cogwheel = 0.0
				creative_encased_crimson_cogwheel = 0.0
				industrial_iron_encased_chain_drive = 0.0
				shadow_steel_encased_warped_shaft = 0.0
				creative_adjustable_chain_gearshift = 0.0
				copper_encased_acacia_large_cogwheel = 0.0
				copper_encased_oak_shaft = 0.0
				industrial_iron_encased_acacia_shaft = 0.0
				brass_encased_cherry_large_cogwheel = 0.0
				industrial_iron_encased_crimson_cogwheel = 0.0
				railway_encased_acacia_cogwheel = 0.0
				shadow_steel_encased_shaft = 0.0
				warped_cogwheel = 0.0
				copper_adjustable_chain_gearshift = 0.0
				brass_encased_mangrove_shaft = 0.0
				creative_encased_mangrove_large_cogwheel = 0.0
				shadow_steel_encased_warped_large_cogwheel = 0.0
				brass_encased_crimson_large_cogwheel = 0.0
				railway_encased_cogwheel = 0.0
				refined_radiance_encased_cogwheel = 0.0
				industrial_iron_encased_bamboo_shaft = 0.0
				refined_radiance_encased_dark_oak_large_cogwheel = 0.0
				shadow_steel_encased_cherry_cogwheel = 0.0
				andesite_encased_cherry_shaft = 0.0
				railway_encased_mangrove_shaft = 0.0
				shadow_steel_encased_birch_cogwheel = 0.0
				brass_encased_glass_shaft = 0.0
				refined_radiance_encased_jungle_shaft = 0.0
				andesite_encased_cherry_cogwheel = 0.0
				railway_encased_bamboo_large_cogwheel = 0.0
				refined_radiance_encased_oak_cogwheel = 0.0
				andesite_encased_crimson_large_cogwheel = 0.0
				oak_shaft = 0.0
				shadow_steel_encased_dark_oak_large_cogwheel = 0.0
				brass_encased_warped_large_cogwheel = 0.0
				industrial_iron_encased_bamboo_large_cogwheel = 0.0
				refined_radiance_encased_acacia_large_cogwheel = 0.0
				refined_radiance_encased_mangrove_cogwheel = 0.0
				refined_radiance_encased_dark_oak_cogwheel = 0.0
				railway_encased_jungle_cogwheel = 0.0
				brass_encased_chain_drive = 0.0
				copper_encased_chain_drive = 0.0
				andesite_encased_crimson_cogwheel = 0.0
				copper_encased_large_cogwheel = 0.0
				brass_adjustable_chain_gearshift = 0.0
				industrial_iron_encased_cherry_cogwheel = 0.0
				dark_oak_large_cogwheel = 0.0
				copper_encased_birch_large_cogwheel = 0.0
				refined_radiance_encased_warped_large_cogwheel = 0.0
				industrial_iron_encased_mangrove_large_cogwheel = 0.0
				copper_encased_glass_shaft = 0.0
				jungle_large_cogwheel = 0.0
				shadow_steel_encased_bamboo_large_cogwheel = 0.0
				copper_encased_cogwheel = 0.0
				creative_encased_warped_shaft = 0.0
				refined_radiance_encased_shaft = 0.0
				spruce_shaft = 0.0
				creative_encased_dark_oak_large_cogwheel = 0.0
				refined_radiance_encased_birch_cogwheel = 0.0
				refined_radiance_encased_crimson_large_cogwheel = 0.0
				copper_encased_mldeg_shaft = 0.0
				creative_encased_oak_large_cogwheel = 0.0
				brass_encased_bamboo_cogwheel = 0.0
				andesite_encased_mangrove_cogwheel = 0.0
				copper_mixer = 4.0
				shadow_steel_encased_acacia_shaft = 0.0
				refined_radiance_encased_birch_shaft = 0.0
				refined_radiance_encased_mangrove_shaft = 0.0
				copper_encased_oak_large_cogwheel = 0.0
				brass_encased_acacia_cogwheel = 0.0
				andesite_encased_jungle_cogwheel = 0.0
				andesite_encased_dark_oak_large_cogwheel = 0.0
				refined_radiance_encased_crimson_cogwheel = 0.0
				andesite_encased_birch_large_cogwheel = 0.0
				creative_encased_crimson_large_cogwheel = 0.0
				railway_press = 8.0
				railway_encased_cherry_cogwheel = 0.0
				industrial_iron_encased_jungle_cogwheel = 0.0
				andesite_encased_oak_shaft = 0.0
				shadow_steel_encased_mangrove_shaft = 0.0
				industrial_iron_encased_cherry_shaft = 0.0
				refined_radiance_encased_spruce_shaft = 0.0
				brass_shaft = 0.0
				birch_large_cogwheel = 0.0
				copper_encased_spruce_shaft = 0.0
				shadow_steel_encased_acacia_large_cogwheel = 0.0
				creative_encased_bamboo_cogwheel = 0.0
				brass_mixer = 4.0
				railway_gearbox = 0.0
				shadow_steel_encased_cherry_large_cogwheel = 0.0
				creative_encased_large_cogwheel = 0.0
				railway_encased_warped_large_cogwheel = 0.0
				railway_encased_mangrove_cogwheel = 0.0
				industrial_iron_encased_dark_oak_cogwheel = 0.0
				railway_encased_jungle_large_cogwheel = 0.0
				andesite_encased_warped_shaft = 0.0
				andesite_encased_oak_large_cogwheel = 0.0
				railway_encased_crimson_cogwheel = 0.0
				industrial_iron_encased_jungle_shaft = 0.0
				creative_encased_glass_shaft = 0.0
				railway_encased_birch_shaft = 0.0
				andesite_encased_mangrove_large_cogwheel = 0.0
				brass_encased_dark_oak_cogwheel = 0.0
				industrial_iron_mixer = 4.0
				industrial_iron_encased_oak_cogwheel = 0.0
				refined_radiance_encased_cherry_cogwheel = 0.0
				industrial_iron_encased_mldeg_shaft = 0.0
				railway_encased_large_cogwheel = 0.0
				refined_radiance_encased_bamboo_shaft = 0.0
				shadow_steel_encased_cherry_shaft = 0.0
				dark_oak_cogwheel = 0.0
				creative_encased_acacia_large_cogwheel = 0.0
				brass_encased_acacia_large_cogwheel = 0.0
				creative_encased_dark_oak_cogwheel = 0.0
				railway_encased_warped_shaft = 0.0
				crimson_large_cogwheel = 0.0
				copper_encased_bamboo_shaft = 0.0
				bamboo_cogwheel = 0.0
				crimson_shaft = 0.0
				industrial_iron_encased_jungle_large_cogwheel = 0.0
				creative_encased_chain_drive = 0.0
				brass_encased_warped_cogwheel = 0.0
				brass_gearbox = 0.0
				creative_mixer = 4.0
				oak_large_cogwheel = 0.0
				shadow_steel_encased_dark_oak_shaft = 0.0
				shadow_steel_encased_birch_shaft = 0.0
				brass_encased_dark_oak_shaft = 0.0
				andesite_encased_mldeg_shaft = 0.0
				shadow_steel_encased_oak_large_cogwheel = 0.0
				industrial_iron_encased_mangrove_cogwheel = 0.0
				shadow_steel_encased_acacia_cogwheel = 0.0
				railway_encased_oak_large_cogwheel = 0.0
				creative_encased_bamboo_large_cogwheel = 0.0
				shadow_steel_encased_mangrove_large_cogwheel = 0.0
				mangrove_shaft = 0.0
				brass_encased_crimson_shaft = 0.0
				copper_encased_dark_oak_cogwheel = 0.0
				shadow_steel_encased_oak_cogwheel = 0.0
				railway_encased_oak_shaft = 0.0
				andesite_encased_dark_oak_shaft = 0.0
				industrial_iron_encased_warped_cogwheel = 0.0
				refined_radiance_encased_bamboo_cogwheel = 0.0
				shadow_steel_encased_mangrove_cogwheel = 0.0
				railway_encased_birch_cogwheel = 0.0
				shadow_steel_encased_jungle_cogwheel = 0.0
				birch_cogwheel = 0.0
				andesite_encased_warped_cogwheel = 0.0
				brass_encased_jungle_shaft = 0.0
				brass_encased_warped_shaft = 0.0
				andesite_encased_bamboo_large_cogwheel = 0.0
				refined_radiance_encased_oak_large_cogwheel = 0.0
				refined_radiance_encased_warped_shaft = 0.0
				copper_encased_crimson_shaft = 0.0
				railway_encased_mldeg_shaft = 0.0
				copper_encased_bamboo_large_cogwheel = 0.0
				creative_encased_warped_cogwheel = 0.0
				railway_encased_dark_oak_shaft = 0.0
				railway_encased_bamboo_cogwheel = 0.0
				railway_encased_jungle_shaft = 0.0
				creative_encased_cherry_shaft = 0.0
				copper_encased_cherry_large_cogwheel = 0.0
				creative_encased_acacia_cogwheel = 0.0
				mangrove_large_cogwheel = 0.0
				railway_encased_oak_cogwheel = 0.0
				shadow_steel_encased_crimson_large_cogwheel = 0.0
				creative_encased_spruce_shaft = 0.0
				shadow_steel_encased_jungle_shaft = 0.0
				shadow_steel_encased_bamboo_cogwheel = 0.0
				industrial_iron_encased_crimson_shaft = 0.0
				brass_encased_oak_cogwheel = 0.0
				industrial_iron_encased_dark_oak_large_cogwheel = 0.0
				warped_large_cogwheel = 0.0
				creative_encased_birch_large_cogwheel = 0.0
				industrial_iron_encased_acacia_cogwheel = 0.0
				creative_encased_oak_cogwheel = 0.0
				shadow_steel_encased_glass_shaft = 0.0
				creative_encased_acacia_shaft = 0.0
				creative_encased_mldeg_shaft = 0.0
				industrial_iron_encased_oak_shaft = 0.0
				railway_encased_dark_oak_large_cogwheel = 0.0
				brass_encased_cherry_shaft = 0.0
				railway_encased_shaft = 0.0
				brass_encased_birch_cogwheel = 0.0
				andesite_encased_acacia_cogwheel = 0.0
				bamboo_large_cogwheel = 0.0
				refined_radiance_encased_bamboo_large_cogwheel = 0.0
				refined_radiance_encased_birch_large_cogwheel = 0.0
				copper_encased_crimson_large_cogwheel = 0.0
				copper_encased_warped_large_cogwheel = 0.0
				copper_encased_birch_cogwheel = 0.0
				industrial_iron_encased_shaft = 0.0
				creative_encased_cherry_large_cogwheel = 0.0
				shadow_steel_encased_large_cogwheel = 0.0
				copper_encased_jungle_shaft = 0.0
				brass_encased_crimson_cogwheel = 0.0
				warped_shaft = 0.0
				railway_encased_crimson_shaft = 0.0
				cherry_cogwheel = 0.0
				birch_shaft = 0.0
				andesite_encased_glass_shaft = 0.0
				copper_encased_oak_cogwheel = 0.0
				copper_encased_cherry_cogwheel = 0.0
				bamboo_shaft = 0.0
				brass_encased_acacia_shaft = 0.0
				refined_radiance_encased_dark_oak_shaft = 0.0
				railway_encased_acacia_shaft = 0.0
				creative_encased_warped_large_cogwheel = 0.0
				industrial_iron_encased_acacia_large_cogwheel = 0.0
				creative_encased_jungle_shaft = 0.0
				industrial_iron_encased_crimson_large_cogwheel = 0.0
				railway_encased_acacia_large_cogwheel = 0.0
				railway_encased_cherry_shaft = 0.0
				andesite_configurable_gearbox = 0.0
				creative_configurable_gearbox = 0.0
				brass_configurable_gearbox = 0.0
				copper_configurable_gearbox = 0.0
				railway_configurable_gearbox = 0.0
				industrial_iron_configurable_gearbox = 0.0

			#.
			#[in Stress Units]
			#Configure how much stress a source can accommodate for.
			[kinetics.stressValues.v2.capacity]
				creative_cogwheel = 16384.0
