#Game settings
[settings]
	#Should Novice and Apprentice Farmers buy this mod's crops? (May reduce chances of other trades appearing)
	farmersBuyDumplingsDelightCrops = true
	#Should the Wandering Trader sell crop seeds, garlic, green onions?
	wanderingTraderSellsDumplingsDelightItems = true

#World generation
[world]
	#Should this mod add some of its items (crop seeds, garlic, green onions) as extra chest loot across Minecraft?
	generateDumplingsDelightChestLoot = true
	#Should Dumplings Delight crops show up planted randomly in various village farms?
	genDumplingsDelightCropsOnVillageFarms = true
