#Enable/disable individual drive types.
[general]
	enable_ender_disk_1k = true
	enable_ender_disk_4k = true
	enable_ender_disk_16k = true
	enable_ender_disk_64k = true
	enable_ender_disk_256k = true
	enable_ender_disk_creative = true
	enable_tape_disk = false

#Controls which network scopes are allowed on ender drives.
[ender_scope]
	#Default scope used for new Ender Drives. Options: global, private, team
	default_scope = "global"
	#Enable global scope
	enable_scope_global = true
	#Enable private scope
	enable_scope_private = true
	#Enable team scope
	enable_scope_team = true
	#Minimum allowed frequency value (Must be <= than max)
	# Default: 0
	# Range: 0 ~ 4095
	frequency_min = 0
	#Maximum allowed frequency value
	# Default: 4095
	# Range: 1 ~ 4095
	frequency_max = 4095

#Configuration for Ender Drive item type limits.
[ender_disk]
	#Max item types for Ender Disk 1k
	# Default: 1
	# Range: 1 ~ 1024
	type_limit_1k = 1
	#Max item types for Ender Disk 4k
	# Default: 31
	# Range: 1 ~ 1024
	type_limit_4k = 31
	#Max item types for Ender Disk 16k
	# Default: 63
	# Range: 1 ~ 1024
	type_limit_16k = 63
	#Max item types for Ender Disk 64k
	# Default: 127
	# Range: 1 ~ 1024
	type_limit_64k = 127
	#Max item types for Ender Disk 256k
	# Default: 255
	# Range: 1 ~ 1024
	type_limit_256k = 255
	#Max item types for Creative Ender Disk
	# Default: 2147483647
	# Range: > 1
	type_limit_creative = 2147483647

#Configuration for tape disk cold storage drives.
[tape_disk]
	#Maximum number of item types allowed in a tape disk (default: 255)
	# Default: 255
	# Range: 1 ~ 1024000
	tape_disk_type_limit = 255
	#Maximum number of item bytes allowed in a tape disk (default: 292144 bytes)
	# Default: 292144
	# Range: 1024 ~ 268435456
	tape_disk_max_bytes = 292144
	#Number of changes before flushing deltaBuffer to disk
	# Default: 500
	# Range: 1 ~ 10000
	flush_threshold = 500
	#Interval (ms) between scheduled flushes to disk
	# Default: 5000
	# Range: 500 ~ 600000
	flush_interval = 5000
	#Milliseconds after last access before a disk is evicted from RAM
	# Default: 300000
	# Range: 60000 ~ 3600000
	ram_eviction_timeout = 300000
	#Enable EXTREMELY verbose debug logging for TapeDB
	debug_log = false

#Configuration for the EnderDB database parameters.
[ender_db]
	#Number of pending WAL entries before merging
	# Default: 100
	# Range: 1 ~ 10000
	merge_buffer_threshold = 1000
	#Minimum time (ms) between WAL commits
	# Default: 2500
	# Range: 100 ~ 60000
	min_commit_interval_ms = 2500
	#Maximum time (ms) between WAL commits
	# Default: 5000
	# Range: 500 ~ 60000
	max_commit_interval_ms = 60000
	#Minimum time (ms) between DB flush commits
	# Default: 5000
	# Range: 500 ~ 60000
	min_db_commit_interval_ms = 5000
	#Maximum time (ms) between DB flush commits
	# Default: 60000
	# Range: 500 ~ 60000
	max_db_commit_interval_ms = 60000
	#Enable EXTREMELY verbose debug logging for EnderDB
	debug_log = false

#Settings for autobenchmark.
[ender_commands]
	#Initial test type count (default: 10,000)
	# Default: 10000
	# Range: 1000 ~ 1000000
	autobenchmark_initial_size = 10000
	#Maximum number of entries attempted during autobenchmark (default: 2,000,000)
	# Default: 2000000
	# Range: 1000 ~ 10000000
	autobenchmark_max_types = 2000000
	#Step size of entries per iteration during autobenchmark (default: 5000)
	# Default: 5000
	# Range: 100 ~ 100000
	autobenchmark_step = 5000
	#Duration of rest between each step in ms (default: 10000)
	# Default: 10000
	# Range: 100 ~ 100000
	autobenchmark_ms_sleep = 10000
	#Minimum TPS to maintain during autobenchmark (default: 18.0)
	# Default: 18.0
	# Range: 1.0 ~ 20.0
	autobenchmark_min_tps = 18.0
