#Amount of ticks for block selection cooldown (default = 2s - 40)
# Default: 40
# Range: 0 ~ 12096000
SelectionCooldown = 40
#Amount of ticks that get added to the block selection cooldown (default = 0)
# Default: 0
# Range: 0 ~ 12096000
SelectionAddedCooldown = 0
#Add range for block selection (default = 12)
# Default: 12
# Range: -8 ~ 128
SelectionMaxRange = 12
#Maximum number of blocks that can be selected (default = 64)
# Default: 64
# Range: 1 ~ 2048
SelectionMaxBlock = 64
#Require Hunger for said selected blocks (default = true)
RequiresHunger = true
#Causes Food Loss to be Multiplied when mining amount of  blocks (default = 2.0)
# Default: 2.0
# Range: 0.0 ~ 1000.0
FoodExhaustionMultiplier = 2.0
#Amount of Hearts to be taken when mining for said block in selection (default = 0)
# Default: 0
# Range: 0 ~ 10000
HealthConsumeAmount = 0
#Amount of Hearts to be taken after mining (default = 0)
# Default: 0
# Range: 0 ~ 10000
HealthConsumeAddedAmount = 0
#Require XP for said selected blocks (default = false)
RequiresXP = false
#Amount of XP ''Points'' to be taken when mining for said block in selection (default = 0)
# Default: 0
# Range: > 0
XPExhaustionAmount = 0
#Require Fuel for said selected blocks (default = false)
RequiresFuelItem = false
#Takes said Vein miner Item Fuel Amount for every Interact/Destroyable Blocks (default = 0)
# Default: 0
# Range: > 0
FuelExhaustionAmount = 0
#Amount of ticks for till you are able to pick up items after blocks drops from selection (default = 0)
# Default: 0
# Range: 0 ~ 30000
ItemPickupDelay = 0
#Amount of ticks for till next block gets broken (default = 2)
# Default: 2
# Range: 0 ~ 100
DelayBetweenBreak = 2
#Amount of blocks between broken blocks (default = 4)
# Default: 4
# Range: 1 ~ 256
BlockPerBreak = 4
#Waits for all blocks to be broken before doing another selection (default = true)
WaitTillBroken = true
#Invert the whitelist behavior (default = true)
InvertWhitelist = true
#Require Hand/Tools for said selected blocks that requires hand/tools to drop //Highly Recommended (default = true)
RequiresMineable = true
#Require Tools for said selected blocks (default = false)
RequiresTools = false
#Prevents Tools being broke when mining/interaction (default = true)
PreventBreakingTool = true
#Sends all dropped Items from Blocks to the Player (default = true)
SendBlocksToPlayer = true
#Ability to Place Blocks by Selection (default = false)
BlockPlacing = false
#Ability to Interact Blocks using said Hand by Selection (default = true)
HandInteraction = true
#Ability to Interact Blocks using said Item by Selection (default = true)
ItemInteraction = true
#Ability to Allow Players to see there selection through Blocks (default = true)
XrayOutlineSelection = true
#Ability to Interact Blocks using said Item by Selection (default = false)
NoDurabilityLoss = false
#Causes to multiply the Mining Speed for every block it accounted for 'Min Speed Multiplier (Set this Higher than Max will Invert)' (default = 0.1)
# Default: 0.1
# Range: 0.0 ~ 1.0
MiningSpeedNerfMin = 0.1
#Causes to multiply the Mining Speed for every block it accounted for 'Max Speed Multiplier (Set this to 0 to disable the speed nerf)' (default = 0.1)
# Default: 0.9
# Range: 0.0 ~ 1.0
MiningSpeedNerfMax = 0.9
#List of block tags for vein mining as in Start Pos Block Tag needs to match said block in selection with the same tag.
VeinBlockTags = ["c:ores", "c:glass_blocks", "c:glass_panes", "c:sands", "c:end_stones", "c:cobblestones", "c:gravels", "c:netherracks", "c:obsidians", "c:ropes", "c:stones", "c:chests", "c:barrels", "c:villager_job_sites", "c:skulls", "minecraft:planks", "minecraft:wool", "minecraft:terracotta", "minecraft:leaves", "minecraft:flowers", "minecraft:replaceable_plants", "minecraft:saplings", "minecraft:fences", "minecraft:walls", "minecraft:wool_carpets", "minecraft:anvil", "minecraft:shulker_boxes", "minecraft:crops", "minecraft:coral_blocks", "minecraft:trap_doors", "minecraft:pressure_plates", "minecraft:buttons", "minecraft:fence_gates", "minecraft:doors", "minecraft:stairs", "minecraft:slabs", "minecraft:sand", "minecraft:dirt", "minecraft:logs", "minecraft:base_stone_overworld", "minecraft:base_stone_nether"]
#for devs (default = false)
Debug = false
