[gui]
	#Enable navigation buttons sound when pressing it
	enableButtonSound = true
	#Enable ModernUI
	enableGuiDebug = false
	#Enable Modern Design for classic GUI when ModernUI is installed
	enableModernDesign = true
