#Defines the cooldown in seconds value for the Galvanized Sheath's ability
#Default is 8]
"Galvanized Sheath CD" = 8
#Defines the cooldown in seconds value for the Scroll Sheath's ability
#Default is [60]
"Scroll Sheath CD" = 60
