#.
#Client-only settings - If you're looking for general settings, look inside your world's serverconfig folder!
[client]
	#.
	#The time to wait before showing the next message in a list.
	# Default: 0.5
	# Range: 0.0 ~ 3.4028234663852886E38
	timeBetweenMessages = 0.5
