	[general.general]
		#If new processes can be created from guest languages.
		graalAllowCreateProcess = false
		#The base energy usage for the scripting drive.
		scriptingDriveBaseConsumption = 2
		#If IO is allowed from guest languages.
		graalAllowIo = false
		#If host class loading is allowed from guest languages.
		graalAllowHostClassLoading = false
		#If new threads can be created from guest languages.
		graalAllowCreateThread = false
		#The minimum number of ticks inbetween sending a script change packet from client to server.
		terminalScriptingClientSyncTickInterval = 20
		#If the native interface can be accessed from guest languages.
		graalAllowNative = false
		#If experimental options can be used in guest languages.
		graalAllowExperimentalOptions = false
		#The base energy usage for the scripting terminal.
		terminalScriptingBaseConsumption = 1
		#The maximum number of lines in stdout and stderr script log files. Set to -1 to disable limit.
		maxLogLines = 2096
		#If environment variables can be accessed from guest languages.
		graalAllowEnvironment = false
		#The maximum number of statements that can be executed in one evaluation. This is to avoid infinite loops or very complex programs. Set to -1 to disable limit (not recommended).
		graalStatementLimit = 16384

	[core.general]
		#If the version checker should be enabled.
		versionChecker = true
