
#Card settings
[card]

	#Fluid Card
	[card.fluid_card]
		#Millibuckets for Fluid Cards without Overclockers installed
		#Range: > 0
		base_milli_buckets_fluid = 5000
		#Multiplier for Overclocker Cards - Number of Overclockers * this value = max millibuckets
		#Range: > 0
		multiplier_milli_buckets_fluid = 10000

	#Energy Card
	[card.energy_card]
		#Maximum FE/T for Energy Cards
		#Range: > 0
		max_fe_tick = 1000000

	#Chemical Card
	[card.chemical_card]
		#Millibuckets for Chemical Cards without Overclockers installed (Only is Mekanism is installed)
		#Range: > 0
		base_milli_buckets_chemical = 15000
		#Multiplier for Overclocker Cards - Number of Overclockers * this value = max millibuckets  (Only is Mekanism is installed)
		#Range: > 0
		multiplier_milli_buckets_chemical = 60000

