[Module]
	#Base range for Sender Mk1 (no range upgrades)
	# Default: 8
	# Range: > 1
	sender1BaseRange = 8
	#Max range for Sender Mk1
	# Default: 16
	# Range: > 1
	sender1MaxRange = 16
	#Base range for Sender Mk2 (no range upgrades)
	# Default: 24
	# Range: > 1
	sender2BaseRange = 24
	#Max range for Sender Mk2
	# Default: 48
	# Range: > 1
	sender2MaxRange = 48
	#Base range for Vacuum (no range upgrades)
	# Default: 6
	# Range: > 1
	vacuumBaseRange = 6
	#Max range for Vacuum
	# Default: 12
	# Range: > 1
	vacuumMaxRange = 12
	#Base range for Extruder Mk1 (no range upgrades)
	# Default: 16
	# Range: > 1
	extruder1BaseRange = 16
	#Max range for Extruder Mk1
	# Default: 32
	# Range: > 1
	extruder1MaxRange = 32
	#Base range for Extruder Mk2 (no range upgrades)
	# Default: 32
	# Range: > 1
	extruder2BaseRange = 32
	#Max range for Extruder Mk2
	# Default: 64
	# Range: > 1
	extruder2MaxRange = 64
	#Base range for Puller Mk2 (no range upgrades)
	# Default: 12
	# Range: > 1
	puller2BaseRange = 12
	#Max range for Puller Mk2
	# Default: 24
	# Range: > 1
	puller2MaxRange = 24
	#Base range for Fluid Mk2 (no range upgrades)
	# Default: 12
	# Range: > 1
	fluid2BaseRange = 12
	#Max range for Fluid Mk2
	# Default: 24
	# Range: > 1
	fluid2MaxRange = 24
	#Should Sender modules show particle effects when working?
	senderParticles = true
	#Should Puller modules show particle effects when working?
	pullerParticles = true
	#Should Placer modules show particle effects when working?
	placerParticles = true
	#Should Breaker modules show particle effects when working?
	breakerParticles = true
	#Should Vacuum modules show particle effects when working?
	vacuumParticles = true
	#Should Flinger modules show smoke effects & play a sound when working?
	flingerEffects = true
	#Should Extruder Mk1/2 modules play a sound when placing/removing blocks?
	extruderSound = true
	#Should Extruder Mk1/2 modules push entities along when extruding blocks?
	extruderPushEntities = true
	#Should Breaker & Extruder Mk1 Modules respect the harvest level of the pickaxe used to craft them? (e.g. craft with an Iron Pickaxe => can't break Obsidian
	breakerHarvestLevelLimit = true
	#Dimension ID's which the Sender Mk3 cannot send to or from, and the Player Module cannot operate (both router dimension and player dimension are checked). This can be wildcarded, e.g. 'somemod:*' blacklists all dimensions added by the mod 'somemod'
	dimensionBlacklist = []

[Router]
	#Base tick interval (in server ticks) for a router; router will run this often
	# Default: 20
	# Range: > 1
	baseTickRate = 20
	#Number of ticks by which 1 Speed Upgrade will reduce the router's tick interval
	# Default: 2
	# Range: > 1
	ticksPerUpgrade = 2
	#Hard minimum tick interval for a router regardless of Speed Upgrades
	# Default: 2
	# Range: > 1
	hardMinTickRate = 2
	#Router with eco mode enabled will go into low-power mode if idle for this many server ticks
	# Default: 100
	# Range: > 1
	ecoTimeout = 100
	#Tick interval for an eco-mode router which has gone into low-power mode
	# Default: 100
	# Range: > 1
	lowPowerTickRate = 100
	#Base fluid transfer rate (mB/t in each direction) for a router
	# Default: 50
	# Range: > 1
	fluidBaseTransferRate = 50
	#Max fluid transfer rate (mB/t in each direction) for a router
	# Default: 400
	# Range: > 1
	fluidMaxTransferRate = 400
	#Fluid transfer rate increase per Fluid Transfer Upgrade
	# Default: 10
	# Range: > 1
	mBperFluidUpgade = 10
	#FE capacity per Energy Upgrade
	# Default: 50000
	# Range: > 1
	fePerEnergyUpgrade = 50000
	#FE transfer rate (FE/t) per Energy Upgrade
	# Default: 1000
	# Range: > 1
	feXferPerEnergyUpgrade = 1000
	#Should block-breaking modules drop XP where appropriate? (ore mining etc.)
	blockBreakXPDrops = true

["Energy Costs"]
	#Energy cost (FE) to run one right-click operation for the Activator Module
	# Default: 0
	# Range: > 0
	activatorModuleEnergyCost = 0
	#Energy cost (FE) to run one left-click (attack) operation for the Activator Module
	# Default: 150
	# Range: > 0
	activatorModuleEnergyCostAttack = 150
	#Energy cost (FE) to run one operation for the Breaker Module
	# Default: 0
	# Range: > 0
	breakerModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Detector Module
	# Default: 0
	# Range: > 0
	detectorModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Distributor Module
	# Default: 0
	# Range: > 0
	distributorModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Dropper Module
	# Default: 0
	# Range: > 0
	dropperModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Energy Distributor Module
	# Default: 0
	# Range: > 0
	energydistributorModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Energy Output Module
	# Default: 0
	# Range: > 0
	energyoutputModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Extruder Module Mk1
	# Default: 0
	# Range: > 0
	extruderModule1EnergyCost = 0
	#Energy cost (FE) to run one operation for the Extruder Module Mk2
	# Default: 0
	# Range: > 0
	extruderModule2EnergyCost = 0
	#Energy cost (FE) to run one operation for the Flinger Module
	# Default: 0
	# Range: > 0
	flingerModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Fluid Module Mk1
	# Default: 0
	# Range: > 0
	fluidModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Fluid Module Mk2
	# Default: 0
	# Range: > 0
	fluidModule2EnergyCost = 0
	#Energy cost (FE) to run one operation for the Placer Module
	# Default: 0
	# Range: > 0
	placerModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Player Module
	# Default: 0
	# Range: > 0
	playerModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Puller Module Mk1
	# Default: 0
	# Range: > 0
	pullerModule1EnergyCost = 0
	#Energy cost (FE) to run one operation for the Puller Module Mk2
	# Default: 0
	# Range: > 0
	pullerModule2EnergyCost = 0
	#Energy cost (FE) to run one operation for the Sender Module Mk1
	# Default: 0
	# Range: > 0
	senderModule1EnergyCost = 0
	#Energy cost (FE) to run one operation for the Sender Module Mk2
	# Default: 0
	# Range: > 0
	senderModule2EnergyCost = 0
	#Energy cost (FE) to run one operation for the Sender Module Mk3
	# Default: 0
	# Range: > 0
	senderModule3EnergyCost = 0
	#Energy cost (FE) to run one operation for the Vacuum Module
	# Default: 0
	# Range: > 0
	vacuumModuleEnergyCost = 0
	#Energy cost (FE) to run one operation for the Void Module
	# Default: 0
	# Range: > 0
	voidModuleEnergyCost = 0

[Sound]
	#Volume of the bleep played when various operations are done with modules/upgrades/etc. such as binding to an inventory, setting camo...
	# Default: 0.5
	# Range: 0.0 ~ 2.0
	bleepVolume = 0.5
