#The reduction of ticks/process each speed augment provides
# Default: 10
# Range: > 0
speedAugmentReduction = 10
#The base speed (in ticks) of the Placer Upgrade
# Default: 60
# Range: > 0
basePlacerSpeed = 60
#The base speed (in ticks) of the Breaker Upgrade
# Default: 60
# Range: > 0
baseBreakerSpeed = 60
#The base speed (in ticks) of the Refill Upgrade
# Default: 60
# Range: > 0
baseRefillSpeed = 60
#The base speed (in ticks) of the Dimensional Refill Upgrade
# Default: 60
# Range: > 0
baseDimensionalRefillSpeed = 60
#The base speed (in ticks) of the Stonecutting Upgrade
# Default: 60
# Range: > 0
baseStonecuttingSpeed = 60
