[general]
	#true : show all recipes
	#false : hide ore not exist recipes (can hide recipes when some mod not installed)
	showOreNotExistRecipes = false
	#Each recipes output item be determined by this list.
	#First is Highest.
	recipeOutputPriority = ["modern_industrialization", "alltheores", "create", "immersiveengineering"]

#processingLevel: Set ores processing max level
#    5 : can into up x5 (able all procssing)
#    4 : can into up x4 (disable ore dissolution, slurry crystalizing)
#    3 : can into up x3 (disable injecting)
#    2 : can into up x2 (disable purifying and clumps crushing)
#    1 : reserved (currently same with 0)
#    0 : disable all processing in this mod
#disabled processing items are hided your world
[ores]

	[ores.aluminum]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.amethyst]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.apatite]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.azure_silver]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.bismuth]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.bort]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.cinnabar]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.cobalt]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.crimson_iron]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.desh]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.dilithium]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.draconium]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.electrotine]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.green_sapphire]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.iridium]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 2
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.lithium]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.nickel]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 5
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.niter]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.peridot]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.platinum]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 2
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.ruby]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.sapphire]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.ostrum]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.calorite]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.silver]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 5
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.sulfur]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.titanium]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 2
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.tungsten]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 2
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.zinc]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 5
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = false

	[ores.coal]
		#Exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"c:dusts/coal"}},"amount":8
		# Default: 0
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.lapis]
		#Exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"c:dusts/lapis"}},"amount":8
		# Default: 0
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.diamond]
		#Exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"c:dusts/diamond"}},"amount":8
		# Default: 0
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.redstone]
		#Exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"c:dusts/redstone"}},"amount":8
		# Default: 0
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.emerald]
		#Exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"c:dusts/emerald"}},"amount":8
		# Default: 0
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.quartz]
		#Exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"c:dusts/quartz"}},"amount":8
		# Default: 0
		# Range: 0 ~ 5
		processingLevel = 0

	[ores.boron]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.magnesium]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.thorium]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 0
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = true

	[ores.antimony]
		# Default: 5
		# Range: 0 ~ 5
		processingLevel = 5
		#Disable recipe what smelting/blasting dust into ingot.
		disableDustCooking = false
