#Storage Settings
[storage]
	#The amount of additional slots the storage stabilizer tier 1 provides. 1 Slot holds one item type.
	# Default: 64
	# Range: > 0
	stabilizerTier1AdditionalMaxItemTypes = 64
	#The amount by which the stabilizer increases the maximum total item count the controller can hold. This is not per slot but the total amount of all items combined.
	# Default: 512000
	# Range: 0 ~ 2147483647
	stabilizerTier1AdditionalMaxTotalItemCount = 512000
	#The amount of slots the storage stabilizer tier 2 provides.
	# Default: 128
	# Range: > 0
	stabilizerTier2AdditionalMaxItemTypes = 128
	#The amount by which the stabilizer increases the maximum total item count the controller can hold. This is not per slot but the total amount of all items combined.
	# Default: 1024000
	# Range: 0 ~ 2147483647
	stabilizerTier2AdditionalMaxTotalItemCount = 1024000
	#The amount of slots the storage stabilizer tier 3 provides.
	# Default: 256
	# Range: > 0
	stabilizerTier3AdditionalMaxItemTypes = 256
	#The amount by which the stabilizer increases the maximum total item count the controller can hold. This is not per slot but the total amount of all items combined.
	# Default: 2048000
	# Range: 0 ~ 2147483647
	stabilizerTier3AdditionalMaxTotalItemCount = 2048000
	#The amount of slots the storage stabilizer tier 4 provides.
	# Default: 512
	# Range: > 0
	stabilizerTier4AdditionalMaxItemTypes = 512
	#The amount by which the stabilizer increases the maximum total item count the controller can hold. This is not per slot but the total amount of all items combined.
	# Default: 4096000
	# Range: 0 ~ 9223372036854775807
	stabilizerTier4AdditionalMaxTotalItemCount = 4096000
	#The amount of slots the storage actuator provides.
	# Default: 128
	# Range: > 0
	controllerMaxItemTypes = 128
	#The stack size the storage actuator uses.
	# Default: 256000
	# Range: 0 ~ 9223372036854775807
	controllerMaxTotalItemCount = 256000
	#True to use the configured controllerStackSize for all items, instead of the stack sizes provided by item type (such as 16 for ender pearls, 64 for iron ingot). WARNING: Setting this to false may have a negative impact on performance.
	unlinkWormholeOnBreak = false
	#The amount of stabilizers tier 4 in the stabilized storage actuator. (Don't auto change the recipe)
	# Default: 7
	# Range: > 0
	stabilizedControllerStabilizers = 7

#Spirit Job Settings
[spirit_job]
	#The duration for the slow falling effect applied by a drikwing.
	# Default: 15
	# Range: > 0
	drikwingFamiliarSlowFallingSeconds = 15
	#The multiplier to each crushing recipe's crushing_time for Tier 1 (Foliot) Crusher Spirits.
	# Default: 2.0
	# Range: 0.0 ~ 1.7976931348623157E308
	tier1CrusherTimeMultiplier = 2.0
	#The multiplier to each crushing recipe's crushing_time for Tier 2 (Djinni) Crusher Spirits.
	# Default: 1.0
	# Range: 0.0 ~ 1.7976931348623157E308
	tier2CrusherTimeMultiplier = 1.0
	#The multiplier to each crushing recipe's crushing_time for Tier 3 (Afrit) Crusher Spirits.
	# Default: 0.5
	# Range: 0.0 ~ 1.7976931348623157E308
	tier3CrusherTimeMultiplier = 0.5
	#The multiplier to each crushing recipe's crushing_time for Tier 4 (Marid) Crusher Spirits.
	# Default: 0.2
	# Range: 0.0 ~ 1.7976931348623157E308
	tier4CrusherTimeMultiplier = 0.2
	#The multiplier to each crushing recipe's output count for Tier 1 (Foliot) Crusher Spirits.
	# Default: 1.0
	# Range: 0.0 ~ 1.7976931348623157E308
	tier1CrusherOutputMultiplier = 1.0
	#The multiplier to each crushing recipe's output count for Tier 2 (Djinni) Crusher Spirits.
	# Default: 1.5
	# Range: 0.0 ~ 1.7976931348623157E308
	tier2CrusherOutputMultiplier = 1.5
	#The multiplier to each crushing recipe's output count for Tier 3 (Afrit) Crusher Spirits.
	# Default: 2.0
	# Range: 0.0 ~ 1.7976931348623157E308
	tier3CrusherOutputMultiplier = 2.0
	#The multiplier to each crushing recipe's output count for Tier 4 (Marid) Crusher Spirits.
	# Default: 3.0
	# Range: 0.0 ~ 1.7976931348623157E308
	tier4CrusherOutputMultiplier = 3.0
	#The minimum ticks before a crusher can pick up an item it dropped. Default is 3 Seconds = 3 * 20 Ticks.
	# Default: 60
	# Range: > 0
	crusherResultPickupDelay = 60
	#The chance for a blacksmith familiar to repair an item (by 2 durability) whenever stone is picked up. 1.0 = 100%, 0.0 = 0%.
	# Default: 0.33
	# Range: 0.0 ~ 1.7976931348623157E308
	blacksmithFamiliarRepairChance = 0.05
	#The amount of iron required for a blacksmith familiar to upgrade another familiar.
	# Default: 18
	# Range: > 0
	blacksmithFamiliarUpgradeCost = 18
	#The cooldown for a blacksmith familiar to upgrade another familiar.
	# Default: 400
	# Range: > 0
	blacksmithFamiliarUpgradeCooldown = 400
	#The multiplier to each smelting recipe's cooking_time for Tier 1 (Foliot) Smelter Spirits.
	# Default: 1.0
	# Range: 0.0 ~ 1.7976931348623157E308
	tier1SmelterTimeMultiplier = 1.0
	#The multiplier to each smelting recipe's cooking_time for Tier 2 (Djinni) Smelter Spirits.
	# Default: 0.5
	# Range: 0.0 ~ 1.7976931348623157E308
	tier2SmelterTimeMultiplier = 0.5
	#The multiplier to each smelting recipe's cooking_time for Tier 3 (Afrit) Smelter Spirits.
	# Default: 0.1
	# Range: 0.0 ~ 1.7976931348623157E308
	tier3SmelterTimeMultiplier = 0.1
	#The multiplier to each smelting recipe's cooking_time for Tier 4 (Marid) Smelter Spirits.
	# Default: 0.01
	# Range: 0.0 ~ 1.7976931348623157E308
	tier4SmelterTimeMultiplier = 0.01
	#The minimum ticks before a crusher can pick up an item it dropped. Default is 3 Seconds = 3 * 20 Ticks.
	# Default: 60
	# Range: > 0
	smelterResultPickupDelay = 60
	#The horizontal value that the upgraded greedy familiar will seek blocks. (Large distances can cause delays in finding)
	# Default: 32
	# Range: > 0
	greedySearchRange = 32
	#The vertical value that the upgraded greedy familiar will seek blocks. (Large distances can cause delays in finding)
	# Default: 16
	# Range: > 0
	greedyVerticalSearchRange = 16
	#The time in ticks it takes to cast the day time ritual.
	# Default: 100
	# Range: > 0
	dayTimeToCast = 100
	#The time in ticks it takes to cast the night time ritual.
	# Default: 100
	# Range: > 0
	nightTimeToCast = 100
	#The time in ticks it takes to cast the rain ritual.
	# Default: 200
	# Range: > 0
	rainTimeToCast = 200
	#The time in ticks it takes to cast the thunder ritual.
	# Default: 300
	# Range: > 0
	thunderTimeToCast = 300
	#The time in ticks it takes to cast the clear weather ritual.
	# Default: 100
	# Range: > 0
	clearWeatherTimeToCast = 100

#Ritual Settings
[rituals]
	#Enables the ritual to clear rainy weather.
	enableClearWeatherRitual = true
	#Enables the ritual to start rainy weather.
	enableRainWeatherRitual = true
	#Enables the ritual to start a thunderstorm.
	enableThunderWeatherRitual = true
	#Enables the ritual to set time to day.
	enableDayTimeRitual = true
	#Enables the ritual to set time to night.
	enableNightTimeRitual = true
	#If enabled, rituals are interrupted if *more* ingredients are present than needed. This should usually be disabled, but can improve performance if (very very) many rituals are running.
	enableRemainingIngredientCountMatching = false
	#Set a value below 1.0 to speed up rituals. Please ensure to use a preceding 0 for values below 1.0, e.g. '0.05' instead of '.05', otherwise Nightconfig (NeoForge's config sytem) will reset the value to 1.0.
	# Default: 1.0
	# Range: 0.05 ~ 1.7976931348623157E308
	ritualDurationMultiplier = 1.0

#Item Settings
[items]
	#Allow the Divining Rod to attune to any ore
	anyOreDivinationRod = false
	#Miners head to the output in the Dimensional Mineshaft before it breaks
	minerOutputBeforeBreak = false
	#Allow miners enchanted with efficiency mine faster
	minerEfficiency = true
	#Allow miners enchanted with fortune to has a chance of mine extra results each operation
	minerFortune = true
	#Don't damage chalks on use
	unbreakableChalks = false
