[PVP_FLAGGING]
	hud_indicator_enabled = true
	#Allowed Values: TopLeft, TopRight, BottomLeft, BottomRight, MiddleBottomLeft, MiddleBottomRight
	hud_indicator_anchor = "BottomLeft"
	hud_indicator_x_offset = 0
	hud_indicator_y_offset = 0
