	###########################################################################################################
	## General settings.
	###########################################################################################################
	[Ribbits.General]
		# If enabled, Pride Ribbits will exist all year instead of only in June.
		# Default: false
		#
		"Show Pride Flags All Year" = false
