#//ALL THESE SETTINGS CAN ALSO BE ACCESSED
#//THROUGH THE IN-GAME SETTING TAB INSIDE
#//THE STARCATCHER'S GUIDE
# Default: 3
# Range: 0 ~ 6
minigame_gui_scale = 3
# Default: 0.0
# Range: -20.0 ~ 20.0
hit_delay = 0.0
#Allowed Values: METRIC, IMPERIAL, CHEESEBURGER, FOOTBALL, DEVELOPER_HEIGHT, BANANA, DUCK, SPACE_WHALE, SCIENTIFIC
units = "METRIC"
#Allowed Values: ALPHABETICAL_UP, ALPHABETICAL_DOWN, MOD_UP, MOD_DOWN, RARITY_UP, RARITY_DOWN, CAUGHT_UP, CAUGHT_DOWN, FLUID_UP, FLUID_DOWN, SEASON_UP, SEASON_DOWN
sort = "RARITY_DOWN"
