[anglers_hat]
	#The amount of extra levels of luck of the sea that are granted by the Angler's Hat
	#Range: 0 ~ 100
	luckOfTheSeaLevelBonus = 1
	#The amount of extra levels of lure that are granted by the Angler's Hat
	#Range: 0 ~ 100
	lureLevelBonus = 1

[antidote_vessel]
	#Whether the Antidote Vessel reduces the duration of negative effects
	#Allowed Values: true, false
	enabled = true
	#The maximum duration in seconds negative mob effects can last when wearing the Antidote Vessel
	#Range: 0 ~ 72000
	maxEffectDuration = 5

[aqua_dashers]
	#Whether the Aqua-Dashers allow the wearer to sprint on water
	#Allowed Values: true, false
	enabled = true

[bunny_hoppers]
	#How much the Bunny Hoppers reduce or increase fall damage
	#Values between -1 and 0 reduce fall damage
	#Values above 0 increase fall damage
	#Range: -Infinity ~ Infinity
	fallDamageMultiplier = 0.0
	#The amount of extra jump strength the Bunny Hoppers apply to players
	#Range: -Infinity ~ Infinity
	jumpStrengthBonus = 0.4
	#The amount of extra safe fall distance in blocks that is granted by the Bunny Hoppers
	#Range: -Infinity ~ Infinity
	safeFallDistanceBonus = 10.0

[charm_of_shrinking]
	#How much the Charm of Shrinking decreases or increases the player's Scale
	#Values between -1 and 0 reduce the player's scale
	#Values above 0 increase the player's scale
	#Range: -Infinity ~ Infinity
	scaleModifier = -0.5

[charm_of_sinking]
	#Whether the Charm of Sinking removes the wearer's collision with water
	#Allowed Values: true, false
	enabled = true

[chorus_totem]
	#Whether the Chorus Totem is consumed after activating
	#Allowed Values: true, false
	consumeOnUse = true
	#The duration in seconds the Chorus Totem goes on cooldown for after activating
	#Range: 0 ~ 72000
	cooldown = 0
	#The amount of health points that are restored after the Chorus Totem activates
	#Range: > 0
	healthRestored = 10
	#The probability that the Chorus Totem activates when a player dies
	#Range: 0.0 ~ 1.0
	teleportationChance = 1.0

[cloud_in_a_bottle]
	#Whether the Cloud in a Bottle allows the wearer to double jump
	#Allowed Values: true, false
	enabled = true
	#The amount of extra safe fall distance in blocks that is granted by the Cloud in a Bottle
	#Range: -Infinity ~ Infinity
	safeFallDistanceBonus = 3.0
	#The amount of extra horizontal velocity that is applied to players that double jump while sprinting using the Cloud in a Bottle
	#Range: > 0.0
	sprintJumpHorizontalVelocity = 0.25
	#The amount of extra vertical velocity that is applied to players that double jump while sprinting using the Cloud in a Bottle
	#Range: > 0.0
	sprintJumpVerticalVelocity = 0.25

[cowboy_hat]
	#How much the Cowboy Hat increases the speed of ridden mounts
	#Range: -Infinity ~ Infinity
	mountSpeedBonus = 0.4

[cross_necklace]
	#The amount of extra ticks the player stays invincible for after taking damage while wearing the Cross Necklace
	#Range: -Infinity ~ Infinity
	bonusInvincibilityTicks = 20.0
	#The duration in seconds the Cross Necklace goes on cooldown for after activating
	#Range: 0 ~ 72000
	cooldown = 0

[crystal_heart]
	#The amount of extra health points that are granted by the Crystal Heart
	#Range: -Infinity ~ Infinity
	healthBonus = 10.0

[digging_claws]
	#How much the Digging Claws increase the wearer's mining speed
	#Range: -Infinity ~ Infinity
	blockBreakSpeedBonus = 0.3
	#The tool tier that the Digging Claws increase the wearer's mining level to
	#Allowed Values: none, wood, stone, iron, diamond, netherite
	toolTier = "stone"

[eternal_steak]
	#The duration in seconds the Eternal Steak goes on cooldown for after being eaten
	#Range: 0 ~ 72000
	cooldown = 15
	#Whether the Eternal Steak can be eaten
	#Allowed Values: true, false
	enabled = true

[everlasting_beef]
	#The duration in seconds the Everlasting Beef goes on cooldown for after being eaten
	#Range: 0 ~ 72000
	cooldown = 15
	#Whether the Everlasting Beef can be eaten
	#Allowed Values: true, false
	enabled = true

[feral_claws]
	#How much the Feral Claws increase the wearer's attack speed
	#Range: -Infinity ~ Infinity
	attackSpeedBonus = 0.3

[fire_gauntlet]
	#How long an entity is set on fire for after being attacked by an entity wearing the Fire Gauntlet
	#Range: -Infinity ~ Infinity
	fireDuration = 8.0

[flame_pendant]
	#The duration in seconds the Flame Pendant goes on cooldown for after setting an entity on fire
	#Range: 0 ~ 72000
	cooldown = 0
	#How long an attacking entity is set on fire for when the Flame Pendant activates
	#Range: 0 ~ 72000
	fireDuration = 10
	#Whether the Flame Pendant grants Fire Resistance after igniting an entity
	#Allowed Values: true, false
	grantFireResistance = true
	#The probability that the Flame Pendant lights an attacker on fire
	#Range: 0.0 ~ 1.0
	strikeChance = 0.4

[flippers]
	#How much the Flippers increase the wearer's swim speed
	#Range: -Infinity ~ Infinity
	swimSpeedBonus = 0.7

[golden_hook]
	#The amount of extra experience dropped by entities that are killed by players wearing the Golden Hook
	#Range: -Infinity ~ Infinity
	entityExperienceBonus = 0.5

[helium_flamingo]
	#The amount of time in seconds a player can fly with the Helium Flamingo before needing to recharge
	#Range: 0 ~ 72000
	flightDuration = 8
	#The amount of time in seconds it takes for the Helium Flamingo to recharge
	#Range: 0 ~ 72000
	rechargeDuration = 15

[kitty_slippers]
	#Whether the Kitty Slippers scare nearby creepers
	#Allowed Values: true, false
	enabled = true

[lucky_scarf]
	#The amount of extra levels of fortune that are granted by the Lucky Scarf
	#Range: 0 ~ 100
	fortuneLevelBonus = 1

[night_vision_goggles]
	#The strength of the night vision effect applied by the Night Vision Goggles
	#Range: 0.0 ~ 1.0
	strength = 0.15

[novelty_drinking_hat]
	#How much the Novelty Drinking Hat increases the wearer's drinking speed
	#Range: -Infinity ~ Infinity
	drinkingSpeedBonus = 1.5
	#How much the Novelty Drinking Hat increases the wearer's eating speed
	#Range: -Infinity ~ Infinity
	eatingSpeedBonus = 0.5

[obsidian_skull]
	#The amount of time in seconds the Obsidian Skull goes on cooldown for after taking fire damage
	#Range: 0 ~ 72000
	cooldown = 60
	#The duration of the fire resistance effect that is applied when taking fire damage while wearing the Obsidian Skull
	#Range: 0 ~ 72000
	fireResistanceDuration = 30

[onion_ring]
	#The duration of haste that is applied per food point eaten while wearing the Onion Ring
	#Range: 0 ~ 72000
	hasteDurationPerFoodPoint = 6
	#The level of the haste effect that is applied by the Onion Ring
	#Range: 0 ~ 256
	hasteLevel = 2

[panic_necklace]
	#The duration in seconds the Panic Necklace goes on cooldown for after taking damage
	#Range: 0 ~ 72000
	cooldown = 0
	#The duration in seconds of the speed effect that is applied when taking damage while wearing the Panic Necklace
	#Range: 0 ~ 72000
	speedDuration = 8
	#The level of the speed effect that is applied by the Panic Necklace
	#Range: 0 ~ 256
	speedLevel = 1

[pickaxe_heater]
	#Whether the Pickaxe Heater smelts mined ores
	#Allowed Values: true, false
	enabled = true

[plastic_drinking_hat]
	#How much the Plastic Drinking Hat increases the wearer's drinking speed
	#Range: -Infinity ~ Infinity
	drinkingSpeedBonus = 1.5
	#How much the Plastic Drinking Hat increases the wearer's eating speed
	#Range: -Infinity ~ Infinity
	eatingSpeedBonus = 0.5

[pocket_piston]
	#The amount of extra knockback that is granted by the Pocket Piston
	#Range: -Infinity ~ Infinity
	attackKnockbackBonus = 0.75

[power_glove]
	#The amount of extra damage that is dealt by melee attacks from players wearing the Power Glove
	#Range: -Infinity ~ Infinity
	attackDamageBonus = 4.0

[rooted_boots]
	#Whether the Rooted Boots replenish hunger when standing on grass
	#Allowed Values: true, false
	enabled = true
	#Whether the Rooted Boots apply a bone meal effect after eating food
	#Allowed Values: true, false
	growPlantsAfterEating = true
	#The amount of time in seconds it takes to replenish a single point of hunger while wearing the Rooted Boots
	#Range: 0 ~ 72000
	hungerReplenishingDuration = 10

[running_shoes]
	#How much the Running Shoes increase the wearer's sprinting speed
	#Range: -Infinity ~ Infinity
	sprintingSpeedBonus = 0.4
	#How much the Running Shoes increase the wearer's step height while sprinting
	#Range: -Infinity ~ Infinity
	sprintingStepHeightBonus = 0.5

[scarf_of_invisibility]
	#Whether the Scarf of Invisibility makes players invisible
	#Allowed Values: true, false
	enabled = true

[shock_pendant]
	#Whether the Shock Pendant cancels damage from lightning
	#Allowed Values: true, false
	cancelLightningDamage = true
	#The amount of time in seconds the Shock Pendant goes on cooldown for after striking an attacker with lightning
	#Range: 0 ~ 72000
	cooldown = 0
	#The probability that the Shock Pendant strikes an attacking entity with lightning
	#Range: 0.0 ~ 1.0
	strikeChance = 0.25

[snorkel]
	#Whether the Snorkel's water breathing effect depletes when underwater
	#Allowed Values: true, false
	isInfinite = false
	#The duration of the water breathing effect that is applied by the Snorkel
	#Range: 0 ~ 72000
	waterBreathingDuration = 15

[snowshoes]
	#Whether the Snowshoes allow the wearer to walk on powdered snow
	#Allowed Values: true, false
	allowWalkingOnPowderedSnow = true
	#How much the Snowshoes increase the wearer's movement speed on snow blocks
	#Range: -Infinity ~ Infinity
	movementSpeedOnSnowBonus = 0.3

[steadfast_spikes]
	#How much knockback resistance is granted by the Steadfast Spikes
	#Range: -Infinity ~ Infinity
	knockbackResistance = 1.0
	#How much the Steadfast Spikes reduce the slipperiness of ice
	#Range: -Infinity ~ Infinity
	slipperinessReduction = 1.0

[strider_shoes]
	#Whether the Strider Shoes make the wearer immune to hot floor damage
	#Allowed Values: true, false
	cancelHotFloorDamage = true
	#Whether the Strider Shoes allow sneaking on lava
	#Allowed Values: true, false
	enabled = true

[superstitious_hat]
	#The amount of extra levels of Looting that are granted by the Superstitious Hat
	#Range: 0 ~ 100
	lootingLevelBonus = 1

[thorn_pendant]
	#The duration in seconds the Thorn Pendant goes on cooldown for after activating
	#Range: 0 ~ 72000
	cooldown = 0
	#The minimum amount of damage that is dealt when the Thorn Pendant activates
	#Range: > 0
	maxDamage = 6
	#The maximum amount of damage that is dealt when the Thorn Pendant activates
	#Range: > 0
	minDamage = 2
	#The probability that the Thorn Pendant damages an attacking entity
	#Range: 0.0 ~ 1.0
	strikeChance = 0.5

[umbrella]
	#Whether the Umbrella slows the player's falling speed when held
	#Allowed Values: true, false
	isGlider = true
	#Whether the Umbrella can be used as a shield
	#Allowed Values: true, false
	isShield = true

[universal_attractor]
	#Whether the Universal Attractor attracts nearby items
	#Allowed Values: true, false
	enabled = true

[vampiric_glove]
	#The probability that damage is absorbed when attacking an entity with the Vampiric Gloves
	#Range: 0.0 ~ 1.0
	absorptionChance = 1.0
	#The proportion of melee damage dealt that is absorbed by the Vampiric Gloves
	#Range: > 0.0
	absorptionRatio = 0.2
	#The maximum amount of healing that can be absorbed in a single hit when attacking an entity while wearing the Vampiric Glove
	#Range: > 0
	maxHealingPerHit = 6

[villager_hat]
	#The amount of extra reputation that is granted by the Villager Hat when trading with villagers
	#Range: -Infinity ~ Infinity
	reputationBonus = 75.0

[warp_drive]
	#The duration Ender Pearls go on cooldown for after being thrown using the Warp Drive
	#Range: 0 ~ 72000
	cooldown = 0
	#Whether the Warp Drive causes ender pearls to not be consumed
	#Allowed Values: true, false
	enabled = true
	#How many hunger points it costs to throw an Ender Pearl using the Warp Drive
	#Range: > 0
	hungerCost = 4
	#Whether the Warp Drive causes Ender Pearls not to deal any damage
	#Allowed Values: true, false
	nullifyEnderPearlDamage = true

[whoopee_cushion]
	#The probability that a fart sound plays when sneaking or double jumping while wearing the Whoopee Cushion
	#Range: 0.0 ~ 1.0
	fartChance = 0.12

[withered_bracelet]
	#The duration the Withered Bracelet goes on cooldown for after inflicting wither on an entity
	#Range: 0 ~ 72000
	cooldown = 0
	#The probability that the Withered Bracelet inflicts a wither effect
	#Range: 0.0 ~ 1.0
	witherChance = 0.3
	#The duration of the wither effect applied by the Withered Bracelet
	#Range: 0 ~ 72000
	witherDuration = 8
	#The level of the wither effect that is inflicted by the Withered Bracelet
	#Range: 0 ~ 256
	witherLevel = 2
