#General settings
[general]
	#Is Enabled?
	enabled = true
	#Cost
	# Default: 0
	# Range: > -2147483648
	cost = 0
	#Is Starter Glyph?
	starter = false
	#The maximum number of times this glyph may appear in a single spell
	# Default: 2147483647
	# Range: > 1
	per_spell_limit = 2147483647
	#The tier of the glyph
	# Default: 2
	# Range: 1 ~ 99
	glyph_tier = 2
