[annihilation]
	#If Annihilation spell can cause blocks to break/create explosion || Default: true
	cause_explosion = true
	#If Annihilation spell can cause fire || Automatically disabled if cause_explosion is disabled || Default: true
	cause_fire = true

[abyssal_blast]
	#Should Abyssal Blast break blocks || Default: true
	should_break_blocks = true
	#Should Abyssal Blast spell deal magic damage (default boss behavior/Ignore armor/less integration with spell power & resist attributes) || Default: false
	should_deal_magic_damage = false

[death_laser]
	#Should DeathLaser break blocks || Default: true
	should_break_blocks = true
	#Should DeathLaser spell deal magic damage (default boss behavior/Ignore armor/less integration with spell power & resist attributes) || Default: false
	should_deal_magic_damage = false

[aerial_collapse]
	#Should bosses take less percent-based damage from Aerial Collapse? || less than 1.0 will make them take less damage || Default 1.0
	# Default: 1.0
	# Range: 0.1 ~ 1.0
	bosses_take_less_damage = 1.0

[summon]
	#Limit the number of active 'Group' summon spells to one at a time || Default: true
	limit_group_summon = true
	#Limit the number of active 'Kaiju' summon spells to one at a time || Default: true
	limit_kaiju_summon = true
	#Limit the number of active 'Miniboss' summon spells to one at a time || Default: true
	limit_miniboss_summon = true

[titanlord_scepter]
	#Damage || Default 9.0
	# Default: 9.0
	# Range: 0.0 ~ 100.0
	damage = 9.0
	#Attack Speed || Default -3.0
	# Default: -3.0
	# Range: -5.0 ~ 5.0
	attack_speed = -3.0
	#Variant Spell Power || MULTIPLY_BASE || Default 0.15
	# Default: 0.15
	# Range: 0.0 ~ 1.0
	variant_spell_power = 0.15
	#Cooldown Reduction || MULTIPLY_BASE || Default 0.15
	# Default: 0.15
	# Range: 0.0 ~ 1.0
	cooldown_reduction = 0.15
	#Mana Regen || MULTIPLY_BASE || Default 0.10
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	mana_regen = 0.1
	#If Titanlord Scepter should grant a recast to Annihilation spell || Default: true
	grant_annihilation_recast = true

[archive_of_abyssal_secrets]
	#Extra spell slots for Archive of abyssal secrets || Default 10 + 2 built-in
	# Default: 10
	# Range: > 4
	extra_slots = 10
	#Max Mana || ADDITION || Default 300.0
	# Default: 300.0
	# Range: 50.0 ~ 1000.0
	max_mana = 300.0
	#Ender Spell Power || MULTIPLY_BASE || Default 0.15
	# Default: 0.15
	# Range: 0.0 ~ 1.0
	ender_spell_power = 0.15
	#Eldritch Spell Power || MULTIPLY_BASE || Default 0.15
	# Default: 0.15
	# Range: 0.0 ~ 1.0
	eldritch_spell_power = 0.15

[chronicles_of_the_firelord]
	#Extra spell slots for Chronicles of the firelord || Default 10 + 2 built-in
	# Default: 10
	# Range: > 3
	extra_slots = 10
	#Max Mana || ADDITION || Default 300.0
	# Default: 300.0
	# Range: 50.0 ~ 1000.0
	max_mana = 300.0
	#Fire Spell Power || MULTIPLY_BASE || Default 0.15
	# Default: 0.15
	# Range: 0.0 ~ 1.0
	fire_spell_power = 0.15
	#Eldritch Spell Power || MULTIPLY_BASE || Default 0.15
	# Default: 0.15
	# Range: 0.0 ~ 1.0
	eldritch_spell_power = 0.15

[the_accused_codex]
	#Extra spell slots for Shellbound || Default 11
	# Default: 11
	# Range: > 1
	extra_slots = 11
	#Max Mana || ADDITION || Default 300.0
	# Default: 300.0
	# Range: 50.0 ~ 1000.0
	max_mana = 300.0
	#Cooldown Reduction || MULTIPLY_BASE || Default 0.10
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	cooldown_reduction = 0.1
	#Ice Spell Power || MULTIPLY_BASE || Default 0.20
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	ice_spell_power = 0.2

[shellbound]
	#Extra spell slots for Shellbound || Default 12
	# Default: 12
	# Range: > 1
	extra_slots = 12
	#Max Mana || ADDITION || Default 200.0
	# Default: 200.0
	# Range: 50.0 ~ 1000.0
	max_mana = 200.0
	#Cooldown Reduction || MULTIPLY_BASE || Default 0.10
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	cooldown_reduction = 0.1
	#Nature Spell Power || MULTIPLY_BASE || Default 0.10
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	nature_spell_power = 0.1
